(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.handtool = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFF5CF").s().p("AARDNQhEgHgZgpQgYglgOhXQgMhKACg5QABgoAbgZIAagRQBrg5A9BJQAXAbAEAgQADAggTALQgfATgbBJQgNAkgHAhQAFAHAvAUQApAXgRAcQgSAdgyAAIgWgBg");
	this.shape.setTransform(59.9,189.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#6699FF").s().p("AgVBmQgKgDgTgQQgRgPgHgKQgFgIgHgSIgJgdQgGgiAWgmQAOgZASgIQAIgDAKAAIATgBQAbAAAJACQASAEAOANQAOAOAFASIAFAWQABAIAGAPQAFANABAIQAGAbgLAbQgMAbgWAKQgMAFgcAAQgZAAgMgFg");
	this.shape_1.setTransform(56.6,280.6,1,1,-15);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFCC99").s().p("AgfCMQgZgDgRgIQgXgLgKgRQgKgRAAgkQgBgkAEgYQAHgjAUgdQAUgeAegTQAQgLAQgEQAKgCAVAAQAmgBAQAOQADADAOATIANAVQAEAKABAQQAIBRgoBAQgdAxgqAIIgPABQgNAAgQgDg");
	this.shape_2.setTransform(34,258,1,1,-15);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF9999").s().p("AgcCUQgrgCgXgbQgLgNgJgaQgNgsAGgiIAGgWQALgjAJgTQAIgPANgRQAOgRAPgJQALgGAbgFQAlgHASADQAUAEAQAOQAPANAHATIAHAfIAHAaQADAQAAAkQAAAYgDAMQgEANgMARQgLAQgJAKQgVAXgfAMQgYAKgZAAIgLgBg");
	this.shape_3.setTransform(20.1,225.5,1,1,-15);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AA0KHQiAgShxhIQkPiuhAl/QgViCAYiPQAwkeDhhBQDvhFDDBkQDABiBVDjQArBzASCHQATCQgPB/QglE1jTBFQhGAWhNAAQgnAAgqgGg");
	this.shape_4.setTransform(57.8,242.2,1,1,-15);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#81B2E0").s().p("AnqNXQhAgWgpg0Qgsg3gJhMQgQiKB2i8QBViICFiGQB1h0B6iLQCTipBVh7QCMjLBjhaQCdiPBUBjQBRBfifDDQhPBhhfBOQgtC0hHDPQhJDUhDCUQhECWg8BVQhOBth1BQQheBCheAAQgvAAgvgRg");
	this.shape_5.setTransform(147.4,87.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AiWBeQgigjgPgjQgPggALgNQASgUAjg4IAfg0QAbgpA+AGQA0AFBAAmQA8AjAjAsQAmAugPAaQgZAwg8BFQgeAigZAZQh8AAhahcg");
	this.shape_6.setTransform(96.1,165.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFF5CF").s().p("AAsDhQg4gBhBghQg+gggrgwQgtg0gDgxQgEg/AEgcQAFgsAYgbQA3g+DLgLIASAFQAXAHAWAMQBHAnAqBNIgKBdQgWBsg8BGQghAog9AAIgDgBg");
	this.shape_7.setTransform(74.4,187.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,212.5,303.8);


(lib.hand = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#81B2E0").s().p("AgWHUQigiDiDkZIhLibQgmhPgLglQgUhGAFg9QAJhvBbg5QBeg7BZASQBOAQAqA/QBPB5A0BFQAzBDA6A+QCaCmBFCiQBoDyinBlQhMAuhNAAQhtAAhvhcg");
	this.shape.setTransform(42.6,57);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhjC2QgUgTg0hXIgwhRQA+igB9giQA+gRAyAQIA6BDQA9BJANAbQARAmgSAvQgWA5hFAyQhEAwhEABIgEABQg1AAgagbg");
	this.shape_1.setTransform(75.6,100.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFF5CF").s().p("AhRCsQhPgjgsg0QgfgkgIg1IgBguQAvhrBRgfQApgQAfAGIBHAgQBUAnA0AlQBEAwAMA+QAIAvgWA1QgQAlhHAXQgzAQg6AEIgJABQgpAAhAgdg");
	this.shape_2.setTransform(99.6,124);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FDCC99").s().p("AhXAWIAYhUICXApIgYBUg");
	this.shape_3.setTransform(124.1,130.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2.8,1,135.7,143.1);


// stage content:
(lib.role01 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// color
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FDCC99").s().p("AhOCoQhmg6gchdQgYhNAfhBQAbg3BqgLQArgFApAFQAoAFAWAMQCaBPgOB+QgDAdgaAjQgbAmgoAaQg2Akg2AAQguAAgugbg");
	this.shape.setTransform(434.7,148.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FDCC99").s().p("AhGCxIgPgHQg7gdgjgoQgiglgNgwQgJgiACgdQAEgsAXglQAagsBLgPQATgEAXgCQAtgFArAGQApAFAZAMIAHADQBAAhAhArQAkAsADA1QACAVgDAVQgFAggbAkQgOARgRAPQgTAQgXAMQgrAXgtABIgVABQgpAAgwgTg");
	this.shape_1.setTransform(433.1,147.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FDCC99").s().p("AhNCyIgPgHQhCgcgkgnQglgmgMgzQgJgkAFgfQAHgsAcgkQAfgrBOgPQAVgEAXgCQAwgEAtAGQAqAGAcAMIAHADQBEAiAiAuQAkAvABA5QAAAWgDAWQgGAjgcAjQgQATgTANQgUAQgaAKQgsATgwgEIgOABQgqAAg9gVg");
	this.shape_2.setTransform(431.6,146.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FDCC99").s().p("AAoDIQgsABhPgXIgQgGQhIgbglgmQgpgogMg2QgIgnAIgfQAMgtAggkQAkgpBQgPQAWgEAZgCQAygEAvAHQAsAGAeANIAHAEQBIAiAjAxQAkAygBA9QAAAXgEAXQgJAngdAiQgQATgVANQgWAOgbAIQgeAKggAAQgSAAgSgDg");
	this.shape_3.setTransform(430,146.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FDCC99").s().p("AApDIQgrgBhXgXIgRgGQhOgZgngmQgsgpgLg4QgIgrALgfQAQgtAkgjQAqgpBTgOQAXgEAZgCQA0gEAyAHQAtAHAhAOIAHADQBNAjAjA1QAkA0gDBBQgBAYgFAYQgKAqgeAiQgRAUgXAMQgYANgdAGQgXAFgYAAQgbAAgcgHg");
	this.shape_4.setTransform(428.4,145.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FDCC99").s().p("AApDIQgpgEhfgWIgSgFQhUgZgoglQgwgqgKg7IAAAAQgIgtAOggQAUguApgiQAugoBWgOQAZgDAagCQA3gEA0AIQAuAGAjAPIAIADQBQAkAlA5QAkA2gGBFQgCAagFAYQgMAtgfAiQgTAUgXALQgaANggADQgPADgQAAQgkAAgogNg");
	this.shape_5.setTransform(426.8,145.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FDCC99").s().p("AApDHQgmgHhogVIgTgFQhbgXgpglQgzgrgKg+IAAgBQgHgvAQggQAZgvAtghQA0gnBZgNQAagEAagCQA6gDA2AIQAvAHAmAPIAIADQBUAlAmA8QAkA4gIBJQgCAcgHAYQgNAxggAiQgUAUgZAKQgcANghABIgQABQgtAAg0gUg");
	this.shape_6.setTransform(425.2,145.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FDCC99").s().p("ACfDhQg2AAhAgbQgkgJhxgVIgTgFQhhgWgqgkQg3gsgJhAIAAgBQgGgzASggQAdgvAyghQA4gmBcgNQAcgEAbgBQA8gEA4AJQAxAHAoAQIAJADQBYAmAmA/QAkA7gKBNQgDAdgHAZQgPA0ghAhQgVAVgbAKQgbAKggAAIgGAAg");
	this.shape_7.setTransform(423.6,145);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FDCC99").s().p("ACkDoQg3gEhEggQghgMh6gUIgUgEQhngVgsgjQg6gtgIhDIAAgBQgGg3AVggQAhgwA3ggQA9glBegMIA6gGQA+gDA7AJQAxAIArAQIAJAEQBcAmAnBDQAkA9gLBRQgFAegHAaQgRA4giAhQgXAVgcAJQgXAIgbAAIgTgBg");
	this.shape_8.setTransform(422,144.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FDCC99").s().p("ACpDuQg5gHhGglQgggOiCgUIgVgEQhtgTgtgjQg+gugHhGIAAgBQgGg5AYghQAlgwA7ggQBDgkBhgMQAegEAdgBQBCgDA8AJQAzAIAtARIAJAEQBhAnAnBGQAkBAgNBVQgGAfgIAbQgSA7gjAgQgYAWgeAIQgVAGgYAAQgNAAgPgCg");
	this.shape_9.setTransform(420.4,144.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FDCC99").s().p("AAqC/QgdgRiLgTQiFgSgzglQhBgwgHhKQgFg8AbghQBXhoC9gWQCpgUCFA0QBkAnAoBKQAlBCgQBZQgdCghjAYQgSAFgUAAQhIAAhjg5g");
	this.shape_10.setTransform(418.8,144.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FDCC99").s().p("AC/EIQgtgHgvgZQgVgKgWgQIgLgHQgMgKgdgJQgZgIgpgIIg9gKIgHgCQiAgVgzgqIgIgGQgZgVgOgZQgXghgEgpQgDgtAOgdQAGgMAIgKQAZgeAjgXQAVgPAZgNQA9ggBTgNIAigDQAjgEAjABQA3AAAxAJQAfAFAdAKIADABQAkALAgAQQAmASAcAZIAFAEQAcAYARAgIAMAWQAKAYAGAXQAJAjAAAqQABASgDASQgCAVgEASQgJAvgVAiQgYApglASQgPAHgQAEQgRAEgSAAQgNAAgPgCg");
	this.shape_11.setTransform(418.9,146.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FDCC99").s().p("AC/EaQgvgJgugbQgTgLgVgTIgKgIQgMgNgcgJQgYgMgpgJIg/gMIgHgCQiAgXg3gwIgHgHQgagXgNgaQgYghgEgrQgEguAQgeQAGgMAIgKQAbgeAlgXQAVgRAZgOQA/giBVgLIAkgDQAjgDAjACQA7ACAwAMQAfAHAdANIACABQAlAMAfATQAlAWAZAcIAFAFQAZAZAOAjIAKAYQAJAZAFAYQAJAiADAsQABATgBASQAAAWgDATQgIAvgVAkQgZArgnASQgPAHgSAEQgPADgQAAQgQAAgSgDg");
	this.shape_12.setTransform(419,147.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FDCC99").s().p("ADAEsQgzgKgrgeQgTgMgUgXIgJgJQgMgPgZgKQgYgOgqgLIhAgOIgIgBQiAgbg5g2IgIgHQgagYgNgbQgZgigEgsQgEgwARgfQAHgLAJgKQAcggAmgXQAVgSAagOQBBglBXgKIAlgDQAkgBAkADQA+AEAwAOQAeAKAcAPIADACQAlAOAeAWQAkAZAVAfIAFAGQAXAaALAnIAIAZIAMAyQAIAiAGAuQADAUAAASQABAYgDASQgFAxgXAmQgZAsgpASQgQAHgSAEQgNACgPAAQgSAAgUgEg");
	this.shape_13.setTransform(419.2,149);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FDCC99").s().p("AC/E/Qg1gMgqghQgRgNgTgaIgJgJQgLgSgYgMQgXgQgrgMIhCgQIgIgCQiAgdg8g8IgIgHQgagagMgcQgbgigEguQgEgyASgfQAHgMAKgKQAdggAogXQAWgTAagPQBDgoBZgIIAmgCQAkgBAmAEQBBAHAvARQAdALAcASIADACQAmARAdAYQAiAcATAjIAEAGQAUAbAJAqIAGAbIAKA0IARBSQADAUABATQADAYgCATQgEAygXAoQgaAtgqASQgRAIgTADQgMABgNAAQgUAAgXgEg");
	this.shape_14.setTransform(419.5,150.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FDCC99").s().p("AC+FRQg4gOgngjQgRgOgSgdIgHgKQgMgVgVgMQgXgTgsgOIhDgSIgIgCQiBgfg/hCIgIgIQgagcgLgbQgdgkgEgwQgEgzAUgfQAHgMAKgLQAfggApgXQAWgVAbgQQBEgpBcgIQATgBAUAAQAlAAAoAFQBCAJAvAUQAdAMAcAVIACACQAoAUAcAbQAgAfAQAmIADAHQASAcAFAuIAFAcQADAeAFAWQAHAjAMAyQAFAVACATQAEAagBASQgCA0gYAqQgbAvgsASQgRAHgTADQgLABgMAAQgXAAgZgGg");
	this.shape_15.setTransform(419.8,151.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FDCC99").s().p("AC9FkQg7gQglglQgQgQgQghIgHgKQgLgYgUgNQgXgVgsgPIhFgUIgIgCQiBgjhChHIgIgIQgagegLgcQgeglgEgxQgFg1AWgfQAIgMAKgLQAgghArgXQAWgWAbgRQBHgsBegGQATgBAUAAQAmABAqAGQBFAMAuAWQAdAOAbAYIADACQAoAWAbAfQAfAhAMAqIADAHQAQAdACAxIACAeQACAgAFAVQAGAjAPA1QAGAVADAUQAFAaAAATQABA1gaAsQgbAwguASQgSAHgTADIgVABQgZAAgbgHg");
	this.shape_16.setTransform(420.1,153.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FDCC99").s().p("AC7F3Qg9gSgjgoQgPgQgPglIgHgKQgKgbgSgOQgXgYgsgRIhHgVIgJgDQiAglhFhNIgIgJQgbgegKgeQgfgmgFgyQgEg3AWgfQAJgNALgLQAhghAtgXQAWgXAcgSQBIguBggFQAUgBAVABQAmABArAIQBIANAtAaQAdAPAbAbIACACQApAYAaAiQAeAkAJAtIADAIQANAegBA1IAAAfQABAhAEAWQAGAjASA3QAHAWAEATQAHAcABATQACA2gaAuQgcAygwASQgSAHgVACIgSABQgbAAgegIg");
	this.shape_17.setTransform(420.5,154.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FDCC99").s().p("AC6GKQhAgUghgrQgOgRgPgoIgFgLQgLgdgPgQQgXgagsgSIhJgXIgJgDQiBgohHhTIgIgJQgbgggKgfQgggmgFg0QgFg4AYghQAKgMALgLQAigiAvgXQAWgYAcgTQBKgxBjgEIApABQAnACAtAJQBKAQAtAcQAcASAbAdIACADQAqAaAZAkQAcAnAGAxIADAJQAKAfgEA4IgBAgQgBAiADAXQAFAiAVA5QAJAXAFAUQAIAdACATQAEA3gbAwQgdAzgxASQgTAHgVACIgPABQgdAAghgJg");
	this.shape_18.setTransform(420.8,156);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FDCC99").s().p("AC4GcQhDgVgfgtQgNgSgNgsIgFgMQgKgggOgQQgWgdgtgTIhLgaIgJgCQiBgrhKhZIgIgJQgcgigIggQgigngFg1QgFg6AZghQAKgMAMgLQAjgjAxgXQAWgaAdgTQBMgzBlgDQAUAAAWABQAnAEAvAKQBNASAsAeQAcAUAaAgIACADQArAcAYAnQAaAqAEA1IACAJQAHAggGA7IgEAiQgCAkADAXQAFAiAYA7IAPAsQAKAdADAUQAGA4gcAyQgdA1g0ASQgTAHgWABIgMABQggAAgjgLg");
	this.shape_19.setTransform(421.2,157.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FDCC99").s().p("AC3GvQhGgXgdgwQgMgTgMgvQgMgsgOgUQgWgggtgVQgJgEhNgaQiIgvhOhmQgcgkgJghQgjgngFg3QgFg8AbghQArgzBDgfQAWgaAdgVQBOg2BngBQA4gBBLASQBQAUAsAiQAbAVAaAjIACADQArAfAXAqQAZAtAAA4IACAJQAFAhgJA/QgKBAADAfQAEAjAbA9QAcA/AFAgQAIA5gdA0QgeA2g1ASQgZAJgcAAQghAAglgMg");
	this.shape_20.setTransform(421.6,158.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FDCC99").s().p("AD2HAQgWgDgXgKIgPgGIgYgNQgTgMgPgLQgXgTgRgWIgFgHQgOgSgMgfIgCgGQgKgZgLgMIgFgHIgbgWQgRgIgXgIIgKgDQgPgFghgOQgMgHgOgFIgRgJIgngVQgbgOgYgQQgcgRgWgSQgWgTgTgWQgKgLgJgNQgSgWgJgXQgGgNgDgOQgQgUgJgYQgLgagCgdQgDgeAFgXQAGgZAOgTIAHgIQAjguA2gfIALgFQAOgRASgPIAVgRIAQgKIAOgIQATgLAUgIQAZgJAbgFQAZgEAcgBIANAAQAkAAAoAHIAeAFIAeAGQAZAGAVAHQAzARAgAYIAIAGIABABQAZAUAYAdIACADIABABQAhAYAUAcQAIALAGAMQATAjAFArQACANAAAOIABAKQADAVgDAfQgCAUgFAbIAAACQgFAdgBAWQgCAaAEAUQAEASAHAWIAUA7IAEALQAKAfACAWQAFARgCANIAAAFQAAAPgDAQQgDATgGAUQgFAPgIARIgCAEQgLAUgOAQQgSATgWAKQgKAEgLADQgPADgQAAQgMAAgNgCg");
	this.shape_21.setTransform(420.2,159.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FDCC99").s().p("ADxHDQgVgEgVgPIgNgIQgLgKgKgGIgggaQgYgUgUgUIgGgGQgQgRgPgYIgDgEQgLgTgLgHIgGgEQgMgEgNgKIgogKIgLgDQgRgEgfgSIgYgOIgQgKIgngYIg0ghQgdgSgWgSQgZgTgTgWQgKgMgJgOQgRgXgKgYQgFgNgDgPQgPgVgJgaQgKgdgCgbQgDgfAFgZQAFgZAPgVIAGgJQAigxA2gjIAKgGQAPgRATgPQAKgKAMgIIAPgKIAPgJQAUgMAVgIQAZgKAcgEQAZgEAeAAIAOAAQAlABApAHIAfAFIAgAGQAZAFAXAIQA1ARAhAYIAIAHIACABQAaAUAZAdIADADIABABQAiAYAVAdQAIAMAHAMQATAkAFAtIABAcIACAKQACAYgEAeQgCATgGAeIAAACQgGAeAAAWQgBAbAGAVIAAAAIAMApIASA9IADAMQAHAggCAWQADAPgFANIgBAFIgHAeQgEATgHAVQgFAPgHASIgDAFQgKAUgPARQgTAUgWAJQgLAEgLABIgQACQgTAAgUgIg");
	this.shape_22.setTransform(419.1,160);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FDCC99").s().p("ADoHHQgTgHgSgTIgLgKQgKgMgJgGQgQgQgPgOQgXgVgXgSIgHgGQgUgOgQgRIgEgDQgNgNgLgBIgGgDQgMACgMgIQgSABgXgFIgKgBQgTgEgdgVQgLgJgMgIQgJgIgHgEIglgbQgbgUgagQQgggSgWgRQgagTgTgXQgKgNgJgOQgRgZgJgYQgGgOgDgQQgOgWgIgcQgKgfgCgbQgDggAFgZQAGgbAOgVIAHgKQAgg2A1glIAKgHQAPgSAUgQIAWgSIARgLIAPgJQAUgNAVgJQAagKAegDQAZgEAgABIAOAAQAnACAqAGIAgAGIAhAFIAyANQA3ARAjAZIAIAHIABABQAcAUAcAdIADAEIABAAQAkAaAVAeQAIALAHANQATAlAFAvQACAPAAAPIABAKQABAZgEAeQgCATgIAgIAAACQgHAgABAWQAAAaAIAXIAAABIANApQAKAfAHAhIACAMQAEAigGAVQABAOgJANIgBAEIgLAdIgNAoIgMAjIgCAGQgLAVgPARQgUAVgXAIQgMAEgLAAIgFAAQgZAAgZgNg");
	this.shape_23.setTransform(418.3,160.7);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FDCC99").s().p("AEVHeQgcgBgagUQgSgIgPgXIgKgMQgIgPgIgGQgOgTgPgOQgXgWgagQIgIgFIgqgXIgEgBQgOgIgMAEIgGAAQgNAIgKgHQgSAGgXgCIgLgBQgUgDgcgZQgKgLgLgIQgIgJgHgFQgVgTgQgLQgagWgbgRQgigTgWgQQgcgTgTgYQgLgNgJgPQgQgZgJgcQgGgNgDgQQgMgYgJgdQgJghgCgbQgCgiAFgaQAFgaAOgYIAHgKQAeg6A1gpIAKgHQAQgSAUgRIAXgSIARgMIAQgJQAUgPAWgIQAagLAfgDQAZgDAiACIAPAAQApADArAGIAhAFIAiAGQAaAFAaAIQA6ARAjAZIAJAHIABABQAeAUAdAdIAEAEIAAAAQAmAcAVAdQAJAMAHAOQATAlAFAyIACAeIABALQABAbgFAeQgDATgIAiIgBACQgHAhABAWQABAZAKAaIAAABIAPAqQAKAgAFAjIABAMQABAjgKAUQgBANgNAMIgCAEIgOAcQgIAUgHAWIgMAkIgCAGQgKAWgRASQgVAWgXAHQgJACgJAAIgGAAg");
	this.shape_24.setTransform(417.5,161.5);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FDCC99").s().p("AEJHnQgbgDgZgYQgRgLgMgbIgIgOQgHgSgHgFQgNgVgPgPQgXgYgdgOIgJgFQgZgKgWgEIgEABQgQgDgMALIgFACQgPAOgJgFQgSAKgWgBQgFABgHgBQgVgCgbgcQgKgMgKgKQgIgLgGgEQgUgWgQgMQgagYgbgRQgkgUgWgPQgegUgUgYQgKgOgJgPQgQgagKgdQgFgPgDgQQgLgZgIgfQgJgjgCgbQgCgiAFgbQAFgcAOgZIAHgKQAcg+A1gsIAJgIQARgSAVgSIAYgTIARgMIAQgKQAVgQAXgJQAagKAhgDQAYgCAlACIAPABQAqADAsAGIAiAFIAkAGQAbAFAbAHQA8ASAkAaIAJAGIACACQAfAUAfAdIAEAEIAAAAQAoAdAVAdQAJANAHAOQAUAnAFAzIABAgIABALQABAcgFAeQgEATgJAkIgBACQgIAjACAWQACAZALAbIABABQALAcAFAPQALAjACAjIAAAMQgBAlgPATQgCAMgRAMIgDADQgJALgJARQgJATgHAXIgMAlIgDAHQgKAWgQATQgWAXgZAGIgOABIgLgBg");
	this.shape_25.setTransform(416.9,162.3);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FDCC99").s().p("AD+HxQgcgGgYgdQgPgNgJgfIgHgPQgFgVgGgGQgMgXgPgPQgXgagggLIgJgFQgdgIgYADIgFACQgRADgNAQIgFAEQgPAUgIgDQgSAPgWABQgFACgHgCQgXgBgZgfQgJgOgJgKQgIgNgGgFQgUgYgPgNQgagagcgRQgmgUgWgPQgggVgTgYQgLgOgJgQQgQgbgJgfIgJghQgKgZgHghQgIgmgCgaQgCgjAFgcQAFgcAOgaIAHgLQAahDA0gvIAKgIQAQgSAWgTIAZgUIASgNIAQgKQAWgRAXgJQAbgKAigDQAYgCAnADIAPABQAsADAtAHQAUACAQAEIAlAEQAbAGAcAHQA+ASAmAaIAJAHIACACQAgAUAiAdIAEADIAAABQAqAdAVAeQAJANAHAPQAUAoAFA2IACAgIAAALQABAfgGAdQgEATgKAlIgBADQgJAkADAXQACAYAOAeIAAABQAOAdAEAOQALAlABAjIgBAOQgEAmgUASQgEAKgUAMIgEADQgMAKgKARQgLATgHAYIgMAnIgCAHQgKAWgRAUQgXAZgZAEIgLABQgIAAgHgCg");
	this.shape_26.setTransform(416.3,163.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FDCC99").s().p("ADyH7QgcgJgXgiQgNgOgHgkIgFgRQgDgXgFgGQgKgagPgQQgXgagjgKIgLgEQgggHgaALIgGADQgSAJgNAVIgGAHQgPAagGgCQgSAVgXACQgFACgHgBQgYgBgYgiQgJgQgIgLQgHgOgFgFQgVgbgOgNQgagdgcgRQgpgVgWgPQgigUgTgaQgLgOgJgRQgPgbgKggQgEgQgEgTQgJgagHgjQgHgngCgaQgCglAFgdQAFgcAOgcIAGgMQAZhGA0gyIAJgJQARgTAXgTIAagVIARgNIARgLQAXgSAXgJQAcgLAjgCQAYgBApADIAQACQAtAEAvAGQAUACAQAEQASABAUAEQAcAEAeAIQBAASAnAbIAKAHIACABQAhAVAjAdIAFADIAAABQArAfAWAeQAJANAIAQQAUAoAFA4IABAiIABALQAAAhgHAdQgEASgLAoIgBACQgKAmAEAXQADAXAPAgIABACQAPAgAEAMQAMAmgCAlIgCANQgHAngYASQgGAJgXALIgFADQgOAJgLARQgNATgIAZIgLAoIgDAIQgJAXgSAUQgYAagaADIgIAAQgKAAgJgCg");
	this.shape_27.setTransform(415.7,163.8);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FDCC99").s().p("ADmIEQgcgLgWgnQgMgRgEgnIgDgTQgCgagEgFQgJgdgPgRQgWgbgmgJIgMgDQgjgFgcASIgGAEQgUAPgOAbIgGAJQgQAggEAAQgTAZgWAEQgGACgGAAQgaAAgXglQgIgSgHgMQgHgQgFgFQgUgegNgOQgagfgdgRQgrgWgWgNQgkgVgTgbQgLgOgJgRQgPgdgJghQgFgQgEgVQgHgagHgmQgHgpgCgaQgCglAFgeQAFgdAOgdIAHgMQAWhLA0g1IAJgJQASgUAXgUIAagVIATgOIARgLQAXgTAYgKQAcgLAkgBQAZgBAqAEIARABIBeALQAWADAQADIAnAFQAdAFAfAHQBCASAoAbIAKAHIACACQAkAVAlAdIAFADIAAABQAtAgAWAfQAJANAIAQQAUAqAFA6IACAjIAAAMQAAAhgIAeIgRA7IgBACQgKAoAEAXQAEAXARAiIABACQARAiADAKQANApgEAlIgDAOQgKApgcARQgIAHgbALIgGADQgQAIgNARQgOASgIAaIgLAqIgCAIQgKAYgTAVQgZAbgaACIgEAAQgMAAgMgEg");
	this.shape_28.setTransform(415.2,164.7);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FDCC99").s().p("ADaIOQgdgOgVgrQgKgTgBgrIgCgWQAAgcgDgFQgHgfgPgSQgXgcgpgHIgNgCQgmgEgeAZIgGAGQgWAUgPAhIgFALQgRAmgDACQgSAdgXAHQgGACgGAAQgcAAgVgoIgNghQgHgQgEgGQgVghgMgOQgaghgegSQgtgXgWgMQglgVgUgbQgLgQgJgRQgOgdgKgkQgEgQgEgVQgHgcgGgnQgGgsgCgZQgCgmAFgfQAFgdAOggIAGgMQAVhPA0g5IAIgJQASgUAZgVIAbgWIASgOIASgLQAYgVAYgJQAdgMAmgBQAYgBAtAFIAQACIBiAMQAWACAQAEQAUABAVADQAdAFAhAIQBEARApAcIALAHIACACQAlAVAmAdIAGAEQAuAhAXAfQAJAOAIARQAUAqAGA9IABAjIAAANQAAAjgJAdIgSA+IgBACQgLApAFAXQAFAXATAkIABACQATAkACAJQAOArgHAlIgEAPQgMAqghAQQgJAGgfALIgHACQgSAHgOARQgQATgIAbQgFAQgGAbIgDAIQgJAZgUAWQgaAcgaABIgCAAQgOAAgNgGg");
	this.shape_29.setTransform(414.7,165.4);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FDCC99").s().p("ACdHXQgJgVACgwQABg0gBgHQgHghgPgTQgagig2gCQgugCgiAnQgYAagPAnIgYA8QgYAsgeACQgdABgTgsQgRgwgGgLQgUgjgLgPQgbgjgegTIhFgjQgngVgUgcQgcgpgQg7QgJgngKhGQgGgugBgZQgDgnAFggQAGgkATgoQAUhSAzg8QAUgZAggbQAYgWAXgPIARgNQAZgVAZgKQAdgMAngBQAZAAAuAGIB1APIAoAFQAwADA6AOQBQAUArAhIACACQAqAWAsAgQAwAjAWAfQAkAyAIBYQAGBEgPAwIgVBAQgMArAGAYQAGAWAVAmQAWAoACAIQAQA1gQAtQgPArgmAQQgLAFgpAMQgVAGgQARQgRASgIAdQgFAQgGAcQgJAegXAbQgbAdgbAAQgygBgdhHg");
	this.shape_30.setTransform(414.1,166.3);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("rgba(253,204,153,0.933)").s().p("ADiIYQgigHgYgvIgEgJQgLgTAAguIAAgQQAAgkgBgHQgDgOgDgLQgGgQgJgLQgLgQgSgJQgUgLgdgBQgXgCgVAJQgTAJgSATQgUAVgOAeIgFAMQgUAwgFAKIAAACQgWAngcAFIgEAAQgeABgUgpIgBgEQgPgrgHgMIgBgCQgUghgLgPQgLgPgMgMQgQgPgSgKIgogVIgdgPQgXgNgQgOQgLgLgIgLQgYgjgOgwIgFgRQgJgkgJhBIgBgIQgGgsgBgZIAAgBQgDgnAFgfIABgHQAHghARgkIAEgOQAUhJAug3QAJgMAMgMQAOgOAQgOQAPgNAOgKIASgOIASgMIAQgNQALgIALgFIAKgFQAWgKAcgCQAJgCAJAAQAVAAAmAEIALABIBCAIIAzAGQAXADAQADQATABAUADQAWADAWAEIAWAFQAyAMAkASQAVAKARAMIACACQAqAVArAfIADACIACABQArAhAXAdIAKAPQAZAqAJA+IACAQQAIBCgNAxIgIAZIgMAnQgLArAFAXIAGASIASAqIAEAJQAQAgABAHIADAMQAGAYgBAXIgBAJIABACQgCAOgEAOQgOArgiAQIgEACQgLAGgiALQgUAHgQARQgNAPgIATIgEAMQgGAQgGAcQgKAdgXAaIgEAEQgZAXgZACIgEABIgNgCg");
	this.shape_31.setTransform(413.9,165.8);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("rgba(253,204,153,0.867)").s().p("ADqIUQghgEgagsIgFgIQgMgSgBgtIgBgPQAAgjgCgIQgCgOgEgLQgFgQgIgLQgMgQgRgJQgUgLgcgCQgXgCgVAIQgTAIgSASQgUAVgPAeIgFALQgUAugGAMIgBABQgVAngcAEIgFABQgeABgUgoIgCgDQgOgpgJgOIgBgCQgTgggLgPQgMgPgMgMQgPgOgTgLIgogUIgdgQQgWgMgQgPQgLgLgIgLQgXgjgOgwIgFgRQgJgkgJhAIgBgIQgGgsgBgYIAAgBQgDgnAFgfIABgHQAHghARgkIAEgOQAThJAtg2QAKgMAMgMQANgNARgOQAOgNAOgLIASgOIARgMIARgNQALgIALgFIAJgFQAXgKAbgDIARgCQAWgBAlAEIALABIBBAIIAzAGIAnAGIAnAEQAVACAXAFIAWAFQAxALAlARQAVAKAQAMIACABQArAWAqAeIADACIACABQArAgAXAdIALAOQAaApAKA8IADAQQAJBBgMAxIgHAZIgLAnQgKAqAEAYIAFASIAQAqIADAIQAOAgACAHIADAMQAFAYgBAXIAAAJIAAACQgCAOgDAOQgLArggARIgDABQgLAIggAMQgSAHgPASQgNAOgJAUIgEALQgGAQgHAbQgLAdgXAYIgFAEQgXAXgaADIgIABIgIgBg");
	this.shape_32.setTransform(413.7,165.4);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("rgba(253,204,153,0.8)").s().p("ADyIQQghgBgbgpIgFgHQgOgRgDgrIgBgPQgBgigCgJIgFgZQgFgPgIgMQgLgQgRgKQgUgLgbgCQgXgDgVAIQgTAIgSARQgVATgPAeIgGALQgSAsgIANIgBACQgVAlgdAFIgFAAQgeACgVgmIgBgEQgOglgKgQIgBgCQgTgggMgPQgMgPgMgMQgOgNgUgLIgngVIgdgPQgXgNgPgPQgLgLgIgLQgXgjgOgvIgFgSQgIgkgJg/IgBgIQgGgrgBgZIAAgBQgDgmAFgfIABgHQAHggARgkIAEgOQAThJAsg2QAKgMALgMQANgNARgOQAOgNAOgLIASgOIARgMIARgNQAKgHALgGIAKgFQAWgKAbgEIARgCQAWgBAkADIALABIBBAIIAyAGIAnAGQATABAUADQAVACAWAFIAWAEQAwALAmARQAVAJAQALIADACQArAVApAeIADACIACABQAqAeAZAdIAKAOQAdApAKA5IAEARQAJA+gKAzIgFAYIgLAnQgJApAEAYIADASQAGAPAIAbIADAIQAMAfABAJIADAMQAEAWAAAYIAAAJIAAACQgBAOgCANQgJAsgdARIgDACQgKAIgeANQgRAJgPARQgNAPgJATIgEALQgHAQgHAaQgMAcgXAYIgFAEQgXAVgZAGIgLAAIgFAAg");
	this.shape_33.setTransform(413.5,164.9);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("rgba(253,204,153,0.733)").s().p("AC9HoIgFgHQgQgQgEgpIgCgPQgCgggCgLIgFgYQgEgQgIgLQgKgQgRgKQgUgMgbgDQgWgCgVAGQgUAHgRARQgVATgQAcIgGAMQgSApgKAQIAAABQgVAkgeAFIgFAAQgeACgVgkIgCgDQgNgjgLgTIgBgCQgTgfgMgPQgMgPgNgLQgMgNgWgLIgngVIgdgPQgXgNgOgQQgLgKgHgMQgXgigOgvIgFgSQgIgkgJg+IgBgIQgGgsgBgYIAAgBQgDgmAFgfIABgHQAGggARgkIAEgNQAThIAsg2QAJgMAMgMQANgOAQgOIAcgXIASgOQAIgHAJgFIAQgNQALgIAKgFIAKgFQAWgLAagEIARgCQAWgCAkADIALABIBBAHIAxAGQAWADARADQATABAUADQAVADAVAEIAWAEQAwAKAmARQAVAJAQAKIADACQAsAVAoAdIADACIACABQApAeAaAcIALAOQAeAoAMA3IAEAQQAKA9gIAzIgFAZIgJAnQgJAoADAZIADARQAFAOAGAcIACAIQALAeAAAKIADALQAEAXAAAYIAAAJIAAACQAAAOgCANQgHArgaASIgCACQgJAJgcAOQgRAJgOASQgMAPgJATIgFALQgHAQgIAYQgMAcgYAXIgFAEQgWATgaAIIgPACIgCAAQggAAgbgkg");
	this.shape_34.setTransform(413.3,164.5);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("rgba(253,204,153,0.667)").s().p("ADDHpIgFgGQgRgPgGgnIgDgPQgCgfgCgLIgFgYQgEgQgIgLQgJgQgRgLQgTgMgagEQgWgCgWAGQgUAGgRAQQgVASgRAcIgGALQgRAngLASIgBABQgVAjgeAFIgFAAQgeACgWgiIgCgDQgNghgMgUIgBgCQgTgegMgQQgMgOgNgLQgMgMgWgMIgogVIgcgPQgXgOgOgPQgKgLgIgLQgWgigOgwIgFgRQgIgkgJg+IgBgIQgGgrgBgYIAAgBQgCgmAEgfIABgGQAHggAQgkIAFgNQAShIAsg2QAJgMALgMQANgNAQgOIAcgYIARgNIARgNIARgMQAKgIAKgFIAKgGQAVgLAagEQAIgCAJgBQAWgCAkADIALAAIBAAIIAxAGIAnAFIAmAEQAWADAUAEIAWAEQAvAKAnAQQAVAIAQALIADABQAsAUAnAdIADACIACABQApAdAbAcIALAOQAgAnAMA1IAFAQQAMA7gHA0IgFAYIgIAnQgIAoACAZIADARQAEANAEAdIACAIQAJAeAAAKIACALQAEAWABAZIAAAIIAAACQAAAOgBANQgEArgYATIgCACQgIALgaAOQgPAKgOASQgMAPgKASIgFALQgHAQgJAYQgNAbgYAWIgFAEQgVASgaAKIgPACIgGABQgdAAgbgfg");
	this.shape_35.setTransform(413.2,164.1);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("rgba(253,204,153,0.6)").s().p("ADKHrIgFgGQgTgNgIgmIgDgPQgDgdgCgNIgFgYQgDgPgHgMQgKgPgQgLQgSgNgbgEQgVgDgWAFQgUAGgSAPQgVARgRAcIgGALQgRAkgMAUIgBABQgVAjgfAEIgFAAQgeACgXggIgCgDQgMgegOgWIgBgCQgSgegNgPQgMgPgMgLQgMgLgXgMIgogVIgcgQQgWgNgPgQQgJgKgIgMQgWgigNgvIgFgRQgIgkgJg9IgBgIQgGgrgBgYIAAgBQgCgmAEgeIABgHQAHggAQgjIAEgNQAThIAqg1QAJgMALgMQANgNAQgOQAOgNAOgLIARgOIARgMIAQgNQAKgHALgFIAJgGQAWgMAZgFIARgCQAWgDAjACIALABIA/AHIAyAGIAmAGIAlAEQAWACAVAFIAWADQAuAJAnAQQAVAIARAKIACABQAtAUAmAdIADABIACACQApAbAbAcIAMANQAhAnAOAzIAFAQQANA5gGA1IgEAYIgHAnQgHAmABAaIACARQAEAMACAeIACAIQAHAdAAAKIACAMQADAVABAZIAAAJIABACQAAAOgBANQgCArgUATIgDACQgGAMgYAPQgOALgOASQgMAPgJASIgGALQgIAQgJAWQgOAbgYAVIgFADQgVASgaALIgOAEIgLABQgaAAgagZg");
	this.shape_36.setTransform(413,163.7);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("rgba(253,204,153,0.533)").s().p("ADRHsIgGgFQgVgMgJglIgDgOIgHgqIgEgYQgDgPgHgLQgJgQgPgLQgTgOgZgEQgWgEgVAFQgVAFgRAOQgWARgRAbIgHALQgQAigOAVIgBACQgVAhgfAFIgFAAQgfACgXgfIgCgDQgLgagQgZIgBgCQgRgdgOgQQgMgOgNgLQgKgKgZgNIgngUIgcgQQgWgOgOgQQgKgKgHgMQgWgigNguIgFgSQgIgkgIg8IgBgIQgGgrgBgYIAAAAQgDgmAFgeIABgHQAGggAQgjIAFgNQAShHAqg1IATgYQANgNAQgOIAbgYIASgOIARgMIAPgMQAKgIALgFIAJgGQAVgMAZgFIARgDQAWgEAiADIALAAIA/AHIAyAGIAlAGIAmAEQAWACAUAEIAWAEQAtAIAoAPQAUAIARAJIADACQAtATAmAcIADACIACABQAoAbAcAcIAMAMQAjAnAOAxIAGAPQAOA4gEA2IgDAXQgCASgEAVQgGAnAAAYIABASQADALABAeIABAIQAFAcAAAMIABALIAEAuIABAJIAAACQACAOgBANQAAArgRAUIgCACQgGAMgWARQgNALgOASQgLAPgKASIgFALIgSAlQgPAagYAUIgFAEQgVAQgaANIgOAFQgIACgIAAQgXAAgYgUg");
	this.shape_37.setTransform(412.8,163.4);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("rgba(253,204,153,0.467)").s().p("ADWHtIgFgEQgXgLgKgjIgEgOIgHgqIgEgXQgDgPgHgMQgIgQgPgMQgSgOgagEQgUgEgWAEQgVAFgTANQgVAQgRAaIgHALQgPAggQAXIgBACQgVAgggAEIgFABQgfACgXgeIgCgCQgLgYgRgbIgBgCQgSgcgNgQQgNgOgMgLQgKgJgZgOIgogUQgQgIgMgIQgWgOgOgPQgJgLgHgMQgWgigMguIgFgSQgIgjgIg9IgBgHQgGgqgBgYIAAgBQgCglAEgeIABgHQAGgfAQgjIAEgOQAShGAqg1QAIgMALgMQAMgNAQgOIAcgYIAQgOIARgMIAQgMIAUgNIAJgGQAVgMAZgGIAQgDQAXgEAhACIALAAIA/AHIAxAGIAlAFIAlAEQAXADATAEIAWADQAsAIApAOQAVAIARAJIACACQAuATAlAbIACACIADABQAnAaAeAbIALAMQAlAnAQAuIAGAPQAPA2gDA3QAAAKgCANQgBASgEAUQgGAnAAAZIAAARQADAKgBAgIAAAIQAEAbgBAMIABALIAFAvIAAAIIABACIACAaQACAsgPAVIgCABQgEAOgUARQgMANgNASQgLAPgKASIgGAKIgTAkQgQAZgYATIgGAEQgTAPgaAQIgOAFQgKAEgKAAQgWAAgXgQg");
	this.shape_38.setTransform(412.7,163);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("rgba(253,204,153,0.4)").s().p("ADbHtIgFgDQgZgKgLghIgFgOIgIgqIgEgXQgCgPgHgLQgIgQgOgMQgSgPgZgFQgUgEgWAEQgVADgTANQgVAPgSAaIgHALQgPAdgSAZIAAACQgVAfghAEIgEABQggACgYgcIgCgCQgKgVgSgdIgBgCQgSgcgOgQQgMgOgNgKQgJgIgagPIgogUQgQgIgMgIQgVgOgOgQQgJgKgHgMQgVgigNguIgEgSQgIgjgIg9IgBgGQgGgrgBgXIAAgBQgCglAEgeIABgHQAFgfAQgjIAFgNQARhFAqg2IATgXQAMgOAPgOIAcgYIAQgNIARgNIAQgLIATgNIAJgGQAVgNAYgGIAQgEQAXgEAhACIALAAIA/AGIAxAHIAkAFIAlAEQAXACATAEIAVADQAsAIApANQAVAIARAIIACACQAvASAkAbIACACIADABQAnAZAeAbIAMAMQAmAmARAsIAGAPQARA0gBA4IgCAXQgBASgDAUQgFAmgBAZIAAARQACAJgDAhIAAAIQACAagBANIAAALIAFAuIAAAJIABACIADAaQAFArgNAWIgBABQgDAPgSASQgMANgMATIgVAgIgGALIgUAiQgRAZgYASIgGAEIgtAfIgOAHQgMAFgNAAQgTAAgVgMg");
	this.shape_39.setTransform(412.7,162.7);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("rgba(253,204,153,0.333)").s().p("ADgHuIgGgDQgagIgNggIgFgNQgGgYgDgSIgDgXQgCgOgGgMQgIgQgOgMQgSgPgYgGQgUgFgWAEQgVADgTAMQgWAOgSAZIgHALQgPAagTAbIgBACQgUAfgiAEIgEAAQggACgYgZIgDgDQgJgSgUgfIgBgCQgRgbgOgQQgNgOgNgKQgIgHgbgPIgogVQgQgIgMgIQgVgOgNgQQgJgKgHgMQgVgigMguIgEgRQgIgkgIg8IgBgGQgGgqgBgYIAAAAQgCglAEgeIABgHQAFgfAQgiIAFgNQARhGAog1QAJgLAKgMQAMgNAPgOIAcgZIAQgNIARgNIAPgLIAUgNIAIgGQAWgOAXgGIAQgEQAXgEAgABIALAAIA+AGIAxAHIAkAFIAlAEQAWACATAEIAWADQArAHAqANQAUAHARAIIACABQAwATAjAaIACABIADACQAmAYAgAbIAMALQAnAlASAqIAHAPQASAyAAA6IgBAWQAAASgDAUIgGA+IgBARQACAJgFAhIgBAIIgBAnIABALIAEAuIABAJIAAACIAFAaQAGArgJAWIgBACQgDAQgQATIgWAgIgVAhIgGAKIgVAhQgSAZgYARIgGADIgtAgIgNAIQgOAIgRAAQgQAAgTgJg");
	this.shape_40.setTransform(412.7,162.4);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("rgba(253,204,153,0.267)").s().p("ADlHuIgGgCQgdgHgOgeIgGgNQgHgXgDgTIgCgWQgCgPgGgMQgHgQgOgMQgRgQgYgGQgUgFgWADQgVACgTALQgWANgTAZIgHALQgOAYgUAdIgBACQgVAdgiAEIgEABQggACgZgYIgDgCIgegwIgBgCQgQgbgPgQQgNgOgNgKQgIgGgcgQIgngUQgQgIgMgIQgVgPgNgQQgJgKgHgMQgUgigMguIgEgRQgIgkgIg7IgBgGQgGgqgBgXIAAgBQgCgkAEgeIABgHQAGgfAPgiIAFgNQARhFAog1IASgXQAMgNAPgOIAbgZIARgNIAQgNIAQgLIATgMIAIgHQAVgOAXgHIAQgEQAXgFAgABIALAAIA9AGIAxAHIAkAEIAkAEQAXADASAEIAWACQAqAHAqAMQAVAHARAIIACABQAwASAjAaIACABIACACQAmAWAhAbIAMALQApAlATAoIAHAPQATAwACA6IAAAWQAAASgDAUIgFA/IgCAQQABAHgHAjIgBAHIgDAoIAAALIAEAuIABAIIABACIAGAaQAJArgHAXIgBABQgBASgOATIgVAiIgVAgIgGAKIgXAgQgTAYgYAQIgGAEQgRALgbAVIgNAJQgRALgUAAQgOAAgPgGg");
	this.shape_41.setTransform(412.8,162.1);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("rgba(253,204,153,0.2)").s().p("ADpHvIgGgCQgegGgQgdIgGgNQgIgVgDgUIgDgWQgBgPgFgMQgHgPgOgNQgQgQgYgHQgTgFgXABQgVACgTALQgWAMgUAYIgHALQgNAWgWAfIgBABQgUAdgjAEIgFAAQggADgZgWIgDgCIgfgwIgBgCQgQgagPgQQgNgOgNgKQgHgGgdgPIgogVQgPgIgMgIQgVgOgNgRQgIgKgHgMQgUgigMgtIgEgSQgIgjgIg7IgBgHQgFgpgBgXQgCglADgdIABgHQAGgfAPgiIAFgMQARhFAng1QAIgLAKgMQAMgNAPgOIAbgYIAQgOIARgNIAPgLIATgMIAIgHQAVgOAWgIIAQgEQAXgFAfAAIALAAQAZACAkAEIAwAGIAkAFIAkAEQAXADASAEIAWACQApAFArANQAUAGASAHIACABQAwASAiAaIACABIADACQAlAVAhAbIANAKQArAkAUAmIAIAPQAUAuADA7IAAAWQABATgCATQgCAjgEAcIgCAPQAAAHgIAjIgCAIIgFAnIAAALQAAASAEAcIABAIIABACIAGAaQAMArgEAXIgBACQAAASgMAVQgIAPgMATIgUAgIgHAKIgXAfQgUAYgYAPIgGADQgRAKgbAXIgMAKQgUAPgZAAQgLAAgMgDg");
	this.shape_42.setTransform(412.8,161.9);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("rgba(253,204,153,0.133)").s().p("ADuHvIgHgCQgggEgRgbIgHgNQgIgUgDgVQgCgLgBgLQAAgOgGgNQgGgPgNgOQgQgQgXgHQgTgGgXABQgVACgUAJQgWAMgUAXIgIALQgMATgYAhIgBACQgUAbgkAFIgEAAQggACgagUIgDgCQgIgKgXglIgBgCQgRgZgPgRQgNgNgNgKQgGgFgfgQIgngUQgPgIgMgIQgVgPgNgRQgIgKgGgMQgUgigMgtIgEgRQgHgkgIg6IgBgHQgGgogBgYQgCgkAEgdIABgHQAFgeAPgiIAGgNQAQhEAng1IARgXQAMgNAOgOIAcgYIAQgOIAQgNIAPgLIASgMIAJgHQAUgPAWgHQAIgDAIgCQAXgGAfAAIALAAQAYACAlAEIAvAGIAkAFIAjAEQAYADARADIAVACQApAFAsAMIAmANIACABQAxARAhAZIACABIACACQAlAVAiAaIANAKQAtAkAUAjIAJAPQAVAtAFA8IABAVQABATgBATQgCAjgEAbIgDARQAAAFgLAjIgCAIIgHAoIgBAKQAAARAFAdIABAIIABACIAHAZQAOAsgBAYIgBACQABATgKAVQgHARgLASQgJAQgMAQIgGAKIgZAeQgUAXgZAOIgGAEQgQAIgbAaIgMAKQgXATgeAAIgPgBg");
	this.shape_43.setTransform(412.9,161.6);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("rgba(253,204,153,0.067)").s().p("ADyHuIgHgBQghgDgTgaIgHgMQgJgTgEgWIgCgWQAAgOgFgMQgGgQgNgOQgQgRgWgHQgTgGgXAAQgVABgTAJQgXALgVAXIgHAKIgmA0IgBACQgUAagkAEIgEAAQghADgagSIgDgCQgIgIgYgnIgBgCQgQgYgQgRQgNgOgOgJQgFgEgfgQIgngVQgQgIgMgIQgUgPgMgRQgIgKgHgMQgTgigLgtIgEgRQgIgkgIg5IgBgHQgFgogBgXQgCgkADgdIABgHQAFgeAQgiIAFgMQAQhEAmg1QAIgLAJgLQALgOAPgOIAbgYIAQgOIAQgNIAPgKIASgNIAIgGQAVgQAVgIIAQgFQAXgGAeAAIALAAQAYABAlAEIAvAGIAkAFIAjAEQAXACARAEIAVACQAoAEAtAMQAUAFARAHIACABQAyARAgAYIACABIADACQAkAUAjAaIANAJQAuAkAWAhIAJAOQAWArAHA9IACAVIAAAmQAAAigFAcIgEAQIgNApIgDAHQgHAYgCAQIgBAKQAAARAEAdIACAIIAAADIAJAYQAQAsACAYIAAACQABAVgIAWQgGARgKATQgJAPgMARIgHAJQgMAQgNANQgWAWgYAOIgHADQgPAIgbAbIgMALQgZAYgkAAIgIAAg");
	this.shape_44.setTransform(412.9,161.5);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("rgba(253,204,153,0)").s().p("ACwHHQgPgaAAglQAAgegXgaQgcgfgzAAQgvAAgmAoIguA9QgUAcgmAEQglAEgegUQgHgEgbgrQgbgrgfgVIhMgoQgpgWgTgbQgcgogQg8QgJgmgKhIQgGgtgBgZQgDgnAFggQAGgjATgpQAUhSAzg8QAUgZAggbQAYgVAXgQIARgMQAZgVAZgLQAdgMAnAAQAZAAAuAGIB1AOIAoAGQAvADA7ANQBQAUArAiIACACQAqAWAsAfQAwAjAWAfQAkAyAIBYQAGBEgPAwIgSAwQgMAdgBAVQgBAQAFAdIABAIIACADQAbA/AFAgQAIA0gvA9QgoA1gvAVQgSAIgjAoQgbAdgrABIgBAAQgwAAgVgmg");
	this.shape_45.setTransform(413,161.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},14).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_22}]},1).to({state:[{t:this.shape_23}]},1).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_26}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_28}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_30}]},1).to({state:[{t:this.shape_31}]},1).to({state:[{t:this.shape_32}]},1).to({state:[{t:this.shape_33}]},1).to({state:[{t:this.shape_34}]},1).to({state:[{t:this.shape_35}]},1).to({state:[{t:this.shape_36}]},1).to({state:[{t:this.shape_37}]},1).to({state:[{t:this.shape_38}]},1).to({state:[{t:this.shape_39}]},1).to({state:[{t:this.shape_40}]},1).to({state:[{t:this.shape_41}]},1).to({state:[{t:this.shape_42}]},1).to({state:[{t:this.shape_43}]},1).to({state:[{t:this.shape_44}]},1).to({state:[{t:this.shape_45}]},1).to({state:[]},1).wait(36));

	// hat
	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#33CCFF").s().p("AgEBbQgEgEACgHIACgMIACgWIgBgNQAAgKgHgYQgLgpgIgSQgFgNgBgFQgBgLAJgFQAGgDAHACQAFACAHAFIAMAMQAFAHAHASIAKAdIACARIACA3QABAbgJAKQgFAFgHADQgFACgFAAQgGAAgEgGg");
	this.shape_46.setTransform(228.9,43);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#33CCFF").s().p("AhkArQgLgJgIgMIgFgKIACgLQAEgLAJgMQAegkBLgHQA8gGAoAfQAVAQAIARQAAAOgPARQgeAihLAIIgZABQgxAAgfgYg");
	this.shape_47.setTransform(228.3,56.8);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#81B2E0").s().p("Am1DzQhFgsALhhQAMhmBkhSQBchLBsgTQBAgLBcAJQAvAEBUggQB1gtAVgFQBKgSBIAYQBOAaAUBAQAYBLgbBFQgeBOhZAiQhQAehRAXIiZAqQhdAehsAWQhrAWhHAAQhIAAgkgWg");
	this.shape_48.setTransform(227.4,74.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_48},{t:this.shape_47},{t:this.shape_46}]}).to({state:[{t:this.shape_48},{t:this.shape_47},{t:this.shape_46}]},14).to({state:[{t:this.shape_48},{t:this.shape_47},{t:this.shape_46}]},10).wait(72));

	// sence
	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#DD9297").s().p("AgyBPQgdgPAAgiQgBgdASgZQASgcAYgPQAegUAhAHQAjAHACAmQACAjgbAlQgXAfgkAKQgPAFgMAAQgLAAgIgEg");
	this.shape_49.setTransform(272.7,139.5);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#F59EA3").s().p("AhPAqQgNgrArgwQAdggApADQAsADAPAmQANAjguApQgqAlgkADIgGABQgfAAgLgmg");
	this.shape_50.setTransform(233.6,138.8);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#663333").s().p("AhNAKQgbgQAHgTIAQAIQAUAIAWAFQBHAMBEgjQgFANgOAOQgdAbguABIgHAAQgvAAgdgSg");
	this.shape_51.setTransform(251.8,183.4);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#663333").s().p("AgPAnQgDgGACgHIAFgNQAFgKADgbQACgLABgDQADgEAEgBQAEgBADACQAGAEgDAMIgFAbIgFAYIgFALQgCAFgDACIgEABQgFAAgDgFg");
	this.shape_52.setTransform(251.7,171.4);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#663333").s().p("AgFA0QgLgBgGgDQgHgDgFgIQgFgEgCgHIgBgSIABgOIADgIIACgJQACgGAKgKQAIgHAGgDIAKgCQAJAAAFACIAKAGIAKAJQADAEADAHIACALQADASgFAMQgDAIgJALQgJAKgGADQgGACgHAAIgFAAg");
	this.shape_53.setTransform(270.5,165);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#663333").s().p("AgLAxQgLgBgHgHIgLgRQgDgJAAgRQAAgLACgEIAMgRIAIgIIAJgFIAMgBQAJAAAFABIAKAFIAJAHQAFAGADAJQAHAWgIAOQgEAJgNAKQgHAGgIAEQgIAEgJAAIgCAAg");
	this.shape_54.setTransform(237,165.9);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#663333").s().p("AhcB0QgegTAGgTIAQAHQASAIAVAEQBHAOBBggQABALgOAOQgdAcgtABIgDAAQgxAAgcgRgAgiAXQgDgGACgHIAFgMQAEgKADgcQAHgSAEgBQAMAFgBAMIgFAcIgGAXIgFALQgHAGgFAAQgDAAgCgDgAiygVQgLgBgHgHIgLgSQgDgIAAgTQAAgKACgFIAUgYQAPgHAGAAQAKAAAFACIAKAFIAJAHQAFAFADAJQAHAXgIAPQgEAIgNAKQgHAHgIADQgIAFgKAAIgCAAgACigbQgLgBgGgEQgHgDgFgHQgFgFgCgHIgBgSIABgOQAHgYAKgJQAIgIAGgDIALgCQAJAAAFACIAKAHIAKAJQADAEADAHIACALQADASgFANQgDAIgJAKQgJAKgGADQgGADgIAAIgFAAg");
	this.shape_55.setTransform(253.9,172.9);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#663333").s().p("AhcB0QgdgUAFgTIAAgBIARAIQASAHAUAFQBIANBAggQABAMgOAOQgcAdgtABIgDABQgyAAgcgSgAgiAWQgDgGACgHIAFgMQAEgKADgcQAHgSAEgBQAMAFgBAMIgFAcIgGAXIgFALQgHAGgFAAQgDAAgCgDgAiygWQgLgBgHgHIgLgSQgDgIAAgTQAAgKACgFIAUgYQAPgHAGAAQAKAAAFACIAKAFIAJAHQAFAFADAJQAHAXgIAPQgEAIgNAKQgHAHgIADQgIAFgKAAIgCAAgACigcQgLgBgGgEQgHgDgFgHQgFgFgCgHIgBgSIABgOQAHgYAKgJQAIgIAGgDIALgCQAJAAAFACIAKAHIAKAJQADAEADAHIACALQADASgFANQgDAIgJAKQgJAKgGADQgGADgIAAIgFAAg");
	this.shape_56.setTransform(254,172.8);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#663333").s().p("AhcBzQgcgTAEgTIAAgBIARAHQASAHAUAFQBIANBBggQgBANgNAOQgdAdgsACIgDAAQgyAAgcgTgAgiAVQgDgFACgIIAFgLQAEgLADgbQAHgSAEgBQAMAEgBANIgFAcIgGAXIgFALQgHAFgFAAQgDAAgCgDgAiygXQgLgBgHgHIgLgRQgDgJAAgSQAAgLACgEIAUgZQAPgGAGAAQAKAAAFABIAKAFIAJAHQAFAGADAJQAHAXgIAOQgEAJgNAKQgHAGgIAEQgIAFgKAAIgCgBgACigdQgLgBgGgDQgHgDgFgIQgFgEgCgHIgBgSIABgPQAHgXAKgKQAIgHAGgDIALgCQAJAAAFACIAKAGIAKAJQADAEADAHIACALQADATgFAMQgDAIgJALQgJAKgGADQgGADgIAAIgFgBg");
	this.shape_57.setTransform(254.2,172.7);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#663333").s().p("AhcBzQgbgTAEgUIgBgBIARAHQASAHAVAFQBIAMBAgeQgBANgNAOQgdAegsABIgFAAQgxAAgbgTgAgiAVQgDgFACgIIAFgLQAEgLADgbQAHgSAEgBQAMAEgBANIgFAcIgGAXIgFALQgHAFgFAAQgDAAgCgDgAiygXQgLgBgHgHIgLgRQgDgJAAgSQAAgLACgEIAUgZQAPgGAGAAQAKAAAFABIAKAFIAJAHQAFAGADAJQAHAXgIAOQgEAJgNAKQgHAGgIAEQgIAEgKAAIgCAAgACigdQgLgBgGgDQgHgDgFgIQgFgEgCgHIgBgSIABgPQAHgXAKgKQAIgHAGgDIALgCQAJAAAFACIAKAGIAKAJQADAEADAHIACALQADATgFAMQgDAIgJALQgJAKgGADQgGACgIAAIgFAAg");
	this.shape_58.setTransform(254.4,172.6);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#663333").s().p("AhcBzQgagTADgUIgBgCIARAHQASAHAVAFQBIAMBBgeQgCAOgOAOQgcAegsACIgFAAQgxAAgbgUgAgiAVQgDgGACgHIAFgMQAEgKADgcQAHgSAEgBQAMAFgBAMIgFAcIgGAXIgFALQgHAGgFAAQgDAAgCgDgAiygXQgLgBgHgHIgLgSQgDgIAAgTQAAgKACgFIAUgYQAPgHAGAAQAKAAAFACIAKAFQAGADADAEQAFAFADAJQAHAXgIAPQgEAIgNAKQgHAHgIADQgIAFgKAAIgCAAgACigdQgLgBgGgEQgHgDgFgHQgFgFgCgHIgBgSIABgOQAHgYAKgJQAIgIAGgDIALgCQAJAAAFACIAKAHIAKAJQADAEADAHIACALQADASgFANQgDAIgJAKQgJAKgGADQgGADgIAAIgFAAg");
	this.shape_59.setTransform(254.6,172.5);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#663333").s().p("AhcBzQgZgUACgUIgBgCIARAHQATAHAUAEQBIAMBBgeQgCAPgNAPQgdAegsACIgEABQgyAAgbgVgAgiAUQgDgGACgHIAFgMQAEgKADgcQAHgSAEgBQAMAFgBAMIgFAcIgGAXIgFALQgHAGgFAAQgDAAgCgDgAiygYQgLgBgHgHIgLgSQgDgIAAgTQAAgKACgFIAUgYQAPgHAGAAQAKAAAFACIAKAFIAJAHQAFAFADAJQAHAXgIAPQgEAIgNAKQgHAHgIADQgIAFgKAAIgCAAgACigeQgLgBgGgEQgHgDgFgHQgFgFgCgHIgBgSIABgOQAHgYAKgJQAIgIAGgDIALgCQAJAAAFACIAKAHIAKAJQADAEADAHIACALQADASgFANQgDAIgJAKQgJAKgGADQgGADgIAAIgFAAg");
	this.shape_60.setTransform(254.7,172.5);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#663333").s().p("AhcBzQgYgUABgUIgBgCIARAGQATAHAUAEQBIAMBCgeQgEAQgNAPQgcAfgsACIgEAAQgyAAgbgVgAgiATQgDgFACgIIAFgLQAEgLADgbQAHgSAEgBQAMAEgBANIgFAcIgGAXIgFALQgHAFgFAAQgDAAgCgDgAiygZQgLgBgHgHIgLgRQgDgJAAgSQAAgLACgEIAUgZQAPgGAGAAQAKAAAFABIAKAFIAJAHQAFAGADAJQAHAXgIAOQgEAJgNAKQgHAGgIAEQgIAFgKAAIgCgBgACigfQgLgBgGgDQgHgDgFgIQgFgEgCgHIgBgSIABgPQAHgXAKgKQAIgHAGgDIALgCQAJAAAFACIAKAGIAKAJQADAEADAHIACALQADATgFAMQgDAIgJALQgJAKgGADQgGADgIAAIgFgBg");
	this.shape_61.setTransform(254.9,172.4);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#663333").s().p("AhcByQgXgTAAgVIgBgCIARAGIAnALQBIAMBCgeQgEARgNAOQgdAggrACIgEABQgzAAgagXgAgiATQgDgGACgHIAFgMQAEgKADgcQAHgSAEgBQAMAFgBAMIgFAcIgGAXIgFALQgHAGgFAAQgDAAgCgDgAiygZQgLgBgHgHIgLgSQgDgIAAgTQAAgKACgFIAUgYQAPgHAGAAQAKAAAFACIAKAFIAJAHQAFAFADAJQAHAXgIAPQgEAIgNAKQgHAHgIADQgIAFgKAAIgCAAgACigfQgLgBgGgEQgHgDgFgHQgFgFgCgHIgBgSIABgOQAHgYAKgJQAIgIAGgDIALgCQAJAAAFACIAKAHIAKAJQADAEADAHIACALQADASgFANQgDAIgJAKQgJAKgGADQgGADgIAAIgFAAg");
	this.shape_62.setTransform(255.1,172.3);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#663333").s().p("AhcByQgWgTgBgVIgBgDIASAGIAmALQBJALBCgdQgFASgNAOQgcAggrADIgEAAQgzAAgbgXgAgiASQgDgFACgIIAFgLQAEgLADgbQAHgSAEgBQAMAEgBANIgFAcIgGAXIgFALQgHAFgFAAQgDAAgCgDgAiygaQgLgBgHgHIgLgRQgDgJAAgSQAAgLACgEIAUgZQAPgGAGAAQAKAAAFABIAKAFIAJAHQAFAGADAJQAHAXgIAOQgEAJgNAKQgHAGgIAEQgIAEgKAAIgCAAgACiggQgLgBgGgDQgHgDgFgIQgFgEgCgHIgBgSIABgPQAHgXAKgKQAIgHAGgDIALgCQAJAAAFACIAKAGIAKAJQADAEADAHIACALQADATgFAMQgDAIgJALQgJAKgGADQgGACgIAAIgFAAg");
	this.shape_63.setTransform(255.3,172.2);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#663333").s().p("AhcByQgVgTgCgWIgBgDIASAGIAmALQBJALBCgdQgGATgMAOQgdAhgqADIgEAAQg0AAgagYgAgiASQgDgGACgHIAFgMQAEgKADgcQAHgSAEgBQAMAFgBAMIgFAcIgGAXIgFALQgHAGgFAAQgDAAgCgDgAiygaQgLgBgHgHIgLgSQgDgIAAgTQAAgKACgFIAUgYQAPgHAGAAQAKAAAFACIAKAFIAJAHQAFAFADAJQAHAXgIAPQgEAIgNAKQgHAHgIADQgIAFgKAAIgCAAgACiggQgLgBgGgEQgHgDgFgHQgFgFgCgHIgBgSIABgOQAHgYAKgJQAIgIAGgDIALgCQAJAAAFACIAKAHIAKAJQADAEADAHIACALQADASgFANQgDAIgJAKQgJAKgGADQgGADgIAAIgFAAg");
	this.shape_64.setTransform(255.5,172.1);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#663333").s().p("AhcByQgUgUgDgWIgBgDIASAGIAnALQBJAKBCgcQgHATgMAPQgdAhgqADIgGAAQgyAAgagYgAgiARQgDgFACgIIAFgLQAEgLADgbQAHgSAEgBQAMAEgBANIgFAcIgGAXIgFALQgHAFgFAAQgDAAgCgDgAiygbQgLgBgHgHIgLgRQgDgJAAgSQAAgLACgEIAUgZQAPgGAGAAQAKAAAFABIAKAFIAJAHQAFAGADAJQAHAXgIAOQgEAJgNAKQgHAGgIAEQgIAFgKAAIgCgBgACighQgLgBgGgDQgHgDgFgIQgFgEgCgHIgBgSIABgPQAHgXAKgKQAIgHAGgDIALgCQAJAAAFACIAKAGIAKAJQADAEADAHIACALQADATgFAMQgDAIgJALQgJAKgGADQgGADgIAAIgFgBg");
	this.shape_65.setTransform(255.6,172);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#663333").s().p("AhcBxQgTgTgEgWIgBgDIASAFIAnALQBJAKBCgcQgHAUgNAPQgcAhgqADIgGABQgzAAgZgagAgiARQgDgGACgHIAFgMQAEgKADgcQAHgSAEgBQAMAFgBAMIgFAcIgGAXIgFALQgHAGgFAAQgDAAgCgDgAiygbQgLgBgHgHIgLgSQgDgIAAgTQAAgKACgFIAUgYQAPgHAGAAQAKAAAFACIAKAFIAJAHQAFAFADAJQAHAXgIAPQgEAIgNAKQgHAHgIADQgIAFgKAAIgCAAgACighQgLgBgGgEQgHgDgFgHQgFgFgCgHIgBgSIABgOQAHgYAKgJQAIgIAGgDIALgCQAJAAAFACIAKAHIAKAJQADAEADAHIACALQADASgFANQgDAIgJAKQgJAKgGADQgGADgIAAIgFAAg");
	this.shape_66.setTransform(255.8,171.9);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#663333").s().p("AhcBxQgSgTgFgWIgBgEIASAFIAnALQBJAKBDgcQgIAVgMAPQgdAigqADIgFAAQgzAAgagagAgiAQQgDgFACgIIAFgLQAEgLADgbQAHgSAEgBQAMAEgBANIgFAcIgGAXIgFALQgHAFgFAAQgDAAgCgDgAiygcQgLgBgHgHIgLgRQgDgJAAgSQAAgLACgEIAUgZQAPgGAGAAQAKAAAFABIAKAFIAJAHQAFAGADAJQAHAXgIAOQgEAJgNAKQgHAGgIAEQgIAEgKAAIgCAAgACigiQgLgBgGgDQgHgDgFgIQgFgEgCgHIgBgSIABgPQAHgXAKgKQAIgHAGgDIALgCQAJAAAFACIAKAGIAKAJQADAEADAHIACALQADATgFAMQgDAIgJALQgJAKgGADQgGACgIAAIgFAAg");
	this.shape_67.setTransform(256,171.8);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#663333").s().p("AhLALQgRgSgGgbIA5APQBGALBGgcQgGASgPASQgeAkgvABIgEAAQguAAgagag");
	this.shape_68.setTransform(254.4,182);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#663333").s().p("AhcBxQgSgTgFgWIgBgEIASAFIAnALQBJAJBDgbQgJAVgMAPQgcAigqADIgGAAQgzAAgZgagAgiAQQgDgFACgIIAFgLQAEgLADgbQAHgSAEgBQAMAEgBANIgFAcIgGAXIgFALQgHAFgFAAQgDAAgCgDgAiygcQgLgBgHgHIgLgRQgDgJAAgSQAAgLACgEIAUgZQAPgGAGAAQAKAAAFABIAKAFIAJAHQAFAGADAJQAHAXgIAOQgEAJgNAKQgHAGgIAEQgIAEgKAAIgCAAgACigiQgLgBgGgDQgHgDgFgIQgFgEgCgHIgBgSIABgPQAHgXAKgKQAIgHAGgDIALgCQAJAAAFACIAKAGIAKAJQADAEADAHIACALQADATgFAMQgDAIgJALQgJAKgGADQgGACgIAAIgFAAg");
	this.shape_69.setTransform(256,171.8);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#663333").s().p("AhcByQgTgUgEgWIgBgDIASAFQATAGAUAFQBJAKBCgcQgHAUgMAPQgdAigqADIgFAAQgzAAgagZgAgiARQgDgGACgHIAFgMQAEgKADgcQAHgSAEgBQAMAFgBAMIgFAcIgGAXIgFALQgHAGgFAAQgDAAgCgDgAiygbQgLgBgHgHIgLgSQgDgIAAgTQAAgKACgFIAUgYQAPgHAGAAQAKAAAFACIAKAFIAJAHQAFAFADAJQAHAXgIAPQgEAIgNAKQgHAHgIADQgIAFgKAAIgCAAgACighQgLgBgGgEQgHgDgFgHQgFgFgCgHIgBgSIABgOQAHgYAKgJQAIgIAGgDIALgCQAJAAAFACIAKAHIAKAJQADAEADAHIACALQADASgFANQgDAIgJAKQgJAKgGADQgGADgIAAIgFAAg");
	this.shape_70.setTransform(255.8,171.9);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#663333").s().p("AhcByQgUgUgDgVIgBgEIASAGIAnALQBIAKBDgcQgHATgMAPQgdAhgqADIgGAAQgyAAgagYgAgiARQgDgFACgIIAFgLQAEgLADgbQAHgSAEgBQAMAEgBANIgFAcIgGAXIgFALQgHAFgFAAQgDAAgCgDgAiygbQgLgBgHgHIgLgRQgDgJAAgSQAAgLACgEIAUgZQAPgGAGAAQAKAAAFABIAKAFIAJAHQAFAGADAJQAHAXgIAOQgEAJgNAKQgHAGgIAEQgIAEgKAAIgCAAgACighQgLgBgGgDQgHgDgFgIQgFgEgCgHIgBgSIABgPQAHgXAKgKQAIgHAGgDIALgCQAJAAAFACIAKAGIAKAJQADAEADAHIACALQADATgFAMQgDAIgJALQgJAKgGADQgGACgIAAIgFAAg");
	this.shape_71.setTransform(255.7,172);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#663333").s().p("AhcByQgVgTgCgWIgBgDIASAGIAmALQBJAKBCgcQgGASgMAPQgdAhgqADIgEAAQg0AAgagYgAgiASQgDgGACgHIAFgMQAEgKADgcQAHgSAEgBQAMAFgBAMIgFAcIgGAXIgFALQgHAGgFAAQgDAAgCgDgAiygaQgLgBgHgHIgLgSQgDgIAAgTQAAgKACgFIAUgYQAPgHAGAAQAKAAAFACIAKAFIAJAHQAFAFADAJQAHAXgIAPQgEAIgNAKQgHAHgIADQgIAFgKAAIgCAAgACiggQgLgBgGgEQgHgDgFgHQgFgFgCgHIgBgSIABgOQAHgYAKgJQAIgIAGgDIALgCQAJAAAFACIAKAHIAKAJQADAEADAHIACALQADASgFANQgDAIgJAKQgJAKgGADQgGADgIAAIgFAAg");
	this.shape_72.setTransform(255.5,172.1);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#663333").s().p("AhcByQgWgTgBgVIgBgDIASAGIAnALQBIALBCgdQgFASgNAPQgcAggrACIgGAAQgyAAgagXgAgiASQgDgFACgIIAFgLQAEgLADgbQAHgSAEgBQAMAEgBANIgFAcIgGAXIgFALQgHAFgFAAQgDAAgCgDgAiygaQgLgBgHgHIgLgRQgDgJAAgSQAAgLACgEIAUgZQAPgGAGAAQAKAAAFABIAKAFIAJAHQAFAGADAJQAHAXgIAOQgEAJgNAKQgHAGgIAEQgIAEgKAAIgCAAgACiggQgLgBgGgDQgHgDgFgIQgFgEgCgHIgBgSIABgPQAHgXAKgKQAIgHAGgDIALgCQAJAAAFACIAKAGIAKAJQADAEADAHIACALQADATgFAMQgDAIgJALQgJAKgGADQgGACgIAAIgFAAg");
	this.shape_73.setTransform(255.3,172.1);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#663333").s().p("AhcByQgXgTAAgVIgBgCIARAGQATAGAUAFQBJALBBgdQgEARgNAPQgcAfgsADIgEAAQgyAAgbgXgAgiATQgDgGACgHIAFgMQAEgKADgcQAHgSAEgBQAMAFgBAMIgFAcIgGAXIgFALQgHAGgFAAQgDAAgCgDgAiygZQgLgBgHgHIgLgSQgDgIAAgTQAAgKACgFIAUgYQAPgHAGAAQAKAAAFACIAKAFIAJAHQAFAFADAJQAHAXgIAPQgEAIgNAKQgHAHgIADQgIAFgKAAIgCAAgACigfQgLgBgGgEQgHgDgFgHQgFgFgCgHIgBgSIABgOQAHgYAKgJQAIgIAGgDIALgCQAJAAAFACIAKAHIAKAJQADAEADAHIACALQADASgFANQgDAIgJAKQgJAKgGADQgGADgIAAIgFAAg");
	this.shape_74.setTransform(255.2,172.2);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#663333").s().p("AhcByQgYgTABgVIgBgCIARAHQATAGAUAFQBIALBCgdQgEAQgNAPQgcAfgsACIgEAAQgyAAgbgWgAgiATQgDgFACgIIAFgLQAEgLADgbQAHgSAEgBQAMAEgBANIgFAcIgGAXIgFALQgHAFgFAAQgDAAgCgDgAiygZQgLgBgHgHIgLgRQgDgJAAgSQAAgLACgEIAUgZQAPgGAGAAQAKAAAFABIAKAFQAGAEADADQAFAGADAJQAHAXgIAOQgEAJgNAKQgHAGgIAEQgIAEgKAAIgCAAgACigfQgLgBgGgDQgHgDgFgIQgFgEgCgHIgBgSIABgPQAHgXAKgKQAIgHAGgDIALgCQAJAAAFACIAKAGIAKAJQADAEADAHIACALQADATgFAMQgDAIgJALQgJAKgGADQgGACgIAAIgFAAg");
	this.shape_75.setTransform(255,172.3);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#663333").s().p("AhcBzQgYgTABgVIgBgCIARAHQATAGAUAFQBIAMBCgeQgDAQgOAOQgcAfgsACIgEAAQgyAAgbgVgAgiAUQgDgGACgHIAFgMQAEgKADgcQAHgSAEgBQAMAFgBAMIgFAcIgGAXIgFALQgHAGgFAAQgDAAgCgDgAiygYQgLgBgHgHIgLgSQgDgIAAgTQAAgKACgFIAUgYQAPgHAGAAQAKAAAFACIAKAFIAJAHQAFAFADAJQAHAXgIAPQgEAIgNAKQgHAHgIADQgIAFgKAAIgCAAgACigeQgLgBgGgEQgHgDgFgHQgFgFgCgHIgBgSIABgOQAHgYAKgJQAIgIAGgDIALgCQAJAAAFACIAKAHIAKAJQADAEADAHIACALQADASgFANQgDAIgJAKQgJAKgGADQgGADgIAAIgFAAg");
	this.shape_76.setTransform(254.8,172.4);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#663333").s().p("AhcBzQgZgTACgVIgBgBIARAHQATAGAUAFQBIAMBBgeQgCAPgOAOQgcAegsACIgEAAQgyAAgbgUgAgiAUQgDgFACgIIAFgLQAEgLADgbQAHgSAEgBQAMAEgBANIgFAcIgGAXIgFALQgHAFgFAAQgDAAgCgDgAiygYQgLgBgHgHIgLgRQgDgJAAgSQAAgLACgEIAUgZQAPgGAGAAQAKAAAFABIAKAFIAJAHQAFAGADAJQAHAXgIAOQgEAJgNAKQgHAGgIAEQgIAEgKAAIgCAAgACigeQgLgBgGgDQgHgDgFgIQgFgEgCgHIgBgSIABgPQAHgXAKgKQAIgHAGgDIALgCQAJAAAFACIAKAGIAKAJQADAEADAHIACALQADATgFAMQgDAIgJALQgJAKgGADQgGACgIAAIgFAAg");
	this.shape_77.setTransform(254.7,172.5);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#663333").s().p("AhcBzQgagTACgUIAAgCIARAHQASAHAUAFQBIAMBBgeQgBAOgOAOQgcAegsACIgDAAQgzAAgbgUgAgiAVQgDgGACgHIAFgMQAEgKADgcQAHgSAEgBQAMAFgBAMIgFAcIgGAXIgFALQgHAGgFAAQgDAAgCgDgAiygXQgLgBgHgHIgLgSQgDgIAAgTQAAgKACgFIAUgYQAPgHAGAAQAKAAAFACIAKAFIAJAHQAFAFADAJQAHAXgIAPQgEAIgNAKQgHAHgIADQgIAFgKAAIgCAAgACigdQgLgBgGgEQgHgDgFgHQgFgFgCgHIgBgSIABgOQAHgYAKgJQAIgIAGgDIALgCQAJAAAFACIAKAHIAKAJQADAEADAHIACALQADASgFANQgDAIgJAKQgJAKgGADQgGADgIAAIgFAAg");
	this.shape_78.setTransform(254.5,172.6);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#663333").s().p("AhcB0QgbgUAEgTIgBgCIARAIQASAHAVAEQBHANBBgfQgBANgNAOQgdAegsABIgFAAQgxAAgbgSgAgiAVQgDgFACgIIAFgLQAEgLADgbQAHgSAEgBQAMAEgBANIgFAcIgGAXIgFALQgHAFgFAAQgDAAgCgDgAiygXQgLgBgHgHIgLgRQgDgJAAgSQAAgLACgEIAUgZQAPgGAGAAQAKAAAFABIAKAFIAJAHQAFAGADAJQAHAXgIAOQgEAJgNAKQgHAGgIAEQgIAEgKAAIgCAAgACigdQgLgBgGgDQgHgDgFgIQgFgEgCgHIgBgSIABgPQAHgXAKgKQAIgHAGgDIALgCQAJAAAFACIAKAGIAKAJQADAEADAHIACALQADATgFAMQgDAIgJALQgJAKgGADQgGACgIAAIgFAAg");
	this.shape_79.setTransform(254.3,172.6);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#663333").s().p("AhcB0QgcgTAEgUIAAgBIARAHQASAIAUAEQBIANBBgfQgBAMgNAOQgdAdgsACIgDAAQgyAAgcgSgAgiAWQgDgGACgHIAFgMQAEgKADgcQAHgSAEgBQAMAFgBAMIgFAcIgGAXIgFALQgHAGgFAAQgDAAgCgDgAiygWQgLgBgHgHIgLgSQgDgIAAgTQAAgKACgFIAUgYQAPgHAGAAQAKAAAFACIAKAFIAJAHQAFAFADAJQAHAXgIAPQgEAIgNAKQgHAHgIADQgIAFgKAAIgCAAgACigcQgLgBgGgEQgHgDgFgHQgFgFgCgHIgBgSIABgOQAHgYAKgJQAIgIAGgDIALgCQAJAAAFACIAKAHIAKAJQADAEADAHIACALQADASgFANQgDAIgJAKQgJAKgGADQgGADgIAAIgFAAg");
	this.shape_80.setTransform(254.2,172.7);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#663333").s().p("AhcB0QgdgTAFgUIAAAAIAQAHQATAHAUAFQBIANBAgfQABALgOAOQgdAdgtABIgCAAQgyAAgcgRgAgiAWQgDgFACgIIAFgLQAEgLADgbQAHgSAEgBQAMAEgBANIgFAcIgGAXIgFALQgHAFgFAAQgDAAgCgDgAiygWQgLgBgHgHIgLgRQgDgJAAgSQAAgLACgEIAUgZQAPgGAGAAQAKAAAFABIAKAFQAGAEADADQAFAGADAJQAHAXgIAOQgEAJgNAKQgHAGgIAEQgIAEgKAAIgCAAgACigcQgLgBgGgDQgHgDgFgIQgFgEgCgHIgBgSIABgPQAHgXAKgKQAIgHAGgDIALgCQAJAAAFACIAKAGIAKAJQADAEADAHIACALQADATgFAMQgDAIgJALQgJAKgGADQgGACgIAAIgFAAg");
	this.shape_81.setTransform(254,172.8);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#663333").s().p("AhcB0QgegTAGgTIARAHQASAIAUAEQBIAOBAggQABALgOAOQgcAcgtABIgDAAQgyAAgcgRgAgiAXQgDgGACgHIAFgMQAEgKADgcQAHgSAEgBQAMAFgBAMIgFAcIgGAXIgFALQgHAGgFAAQgDAAgCgDgAiygVQgLgBgHgHIgLgSQgDgIAAgTQAAgKACgFIAUgYQAPgHAGAAQAKAAAFACIAKAFIAJAHQAFAFADAJQAHAXgIAPQgEAIgNAKQgHAHgIADQgIAFgKAAIgCAAgACigbQgLgBgGgEQgHgDgFgHQgFgFgCgHIgBgSIABgOQAHgYAKgJQAIgIAGgDIALgCQAJAAAFACIAKAHIAKAJQADAEADAHIACALQADASgFANQgDAIgJAKQgJAKgGADQgGADgIAAIgFAAg");
	this.shape_82.setTransform(253.8,172.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_54,p:{x:237,y:165.9}},{t:this.shape_53,p:{x:270.5,y:165}},{t:this.shape_52,p:{x:251.7,y:171.4}},{t:this.shape_51},{t:this.shape_50,p:{y:138.8,x:233.6}},{t:this.shape_49,p:{y:139.5}}]}).to({state:[{t:this.shape_50,p:{y:138.7,x:233.6}},{t:this.shape_55},{t:this.shape_49,p:{y:139.3}}]},1).to({state:[{t:this.shape_50,p:{y:138.5,x:233.5}},{t:this.shape_56},{t:this.shape_49,p:{y:139.2}}]},1).to({state:[{t:this.shape_50,p:{y:138.4,x:233.4}},{t:this.shape_57},{t:this.shape_49,p:{y:139}}]},1).to({state:[{t:this.shape_50,p:{y:138.3,x:233.3}},{t:this.shape_58},{t:this.shape_49,p:{y:138.8}}]},1).to({state:[{t:this.shape_50,p:{y:138.1,x:233.3}},{t:this.shape_59},{t:this.shape_49,p:{y:138.6}}]},1).to({state:[{t:this.shape_50,p:{y:138,x:233.2}},{t:this.shape_60},{t:this.shape_49,p:{y:138.5}}]},1).to({state:[{t:this.shape_50,p:{y:137.8,x:233.1}},{t:this.shape_61},{t:this.shape_49,p:{y:138.3}}]},1).to({state:[{t:this.shape_50,p:{y:137.7,x:233.1}},{t:this.shape_62},{t:this.shape_49,p:{y:138.1}}]},1).to({state:[{t:this.shape_50,p:{y:137.5,x:233}},{t:this.shape_63},{t:this.shape_49,p:{y:137.9}}]},1).to({state:[{t:this.shape_50,p:{y:137.4,x:232.9}},{t:this.shape_64},{t:this.shape_49,p:{y:137.7}}]},1).to({state:[{t:this.shape_50,p:{y:137.3,x:232.8}},{t:this.shape_65},{t:this.shape_49,p:{y:137.6}}]},1).to({state:[{t:this.shape_50,p:{y:137.1,x:232.8}},{t:this.shape_66},{t:this.shape_49,p:{y:137.4}}]},1).to({state:[{t:this.shape_50,p:{y:137,x:232.7}},{t:this.shape_67},{t:this.shape_49,p:{y:137.2}}]},1).to({state:[{t:this.shape_54,p:{x:239.5,y:163.9}},{t:this.shape_53,p:{x:273,y:163}},{t:this.shape_52,p:{x:254.2,y:169.4}},{t:this.shape_68},{t:this.shape_50,p:{y:136.8,x:232.6}},{t:this.shape_49,p:{y:137}}]},1).to({state:[{t:this.shape_54,p:{x:239.5,y:163.9}},{t:this.shape_53,p:{x:273,y:163}},{t:this.shape_52,p:{x:254.2,y:169.4}},{t:this.shape_68},{t:this.shape_50,p:{y:136.8,x:232.6}},{t:this.shape_49,p:{y:137}}]},10).to({state:[{t:this.shape_54,p:{x:239.5,y:163.9}},{t:this.shape_53,p:{x:273,y:163}},{t:this.shape_52,p:{x:254.2,y:169.4}},{t:this.shape_68},{t:this.shape_50,p:{y:136.8,x:232.6}},{t:this.shape_49,p:{y:137}}]},20).to({state:[{t:this.shape_50,p:{y:137,x:232.7}},{t:this.shape_69},{t:this.shape_49,p:{y:137.2}}]},1).to({state:[{t:this.shape_50,p:{y:137.1,x:232.8}},{t:this.shape_70},{t:this.shape_49,p:{y:137.4}}]},1).to({state:[{t:this.shape_50,p:{y:137.2,x:232.8}},{t:this.shape_71},{t:this.shape_49,p:{y:137.5}}]},1).to({state:[{t:this.shape_50,p:{y:137.4,x:232.9}},{t:this.shape_72},{t:this.shape_49,p:{y:137.7}}]},1).to({state:[{t:this.shape_50,p:{y:137.5,x:233}},{t:this.shape_73},{t:this.shape_49,p:{y:137.9}}]},1).to({state:[{t:this.shape_50,p:{y:137.6,x:233}},{t:this.shape_74},{t:this.shape_49,p:{y:138}}]},1).to({state:[{t:this.shape_50,p:{y:137.8,x:233.1}},{t:this.shape_75},{t:this.shape_49,p:{y:138.2}}]},1).to({state:[{t:this.shape_50,p:{y:137.9,x:233.2}},{t:this.shape_76},{t:this.shape_49,p:{y:138.4}}]},1).to({state:[{t:this.shape_50,p:{y:138,x:233.2}},{t:this.shape_77},{t:this.shape_49,p:{y:138.5}}]},1).to({state:[{t:this.shape_50,p:{y:138.2,x:233.3}},{t:this.shape_78},{t:this.shape_49,p:{y:138.7}}]},1).to({state:[{t:this.shape_50,p:{y:138.3,x:233.4}},{t:this.shape_79},{t:this.shape_49,p:{y:138.9}}]},1).to({state:[{t:this.shape_50,p:{y:138.4,x:233.4}},{t:this.shape_80},{t:this.shape_49,p:{y:139}}]},1).to({state:[{t:this.shape_50,p:{y:138.6,x:233.5}},{t:this.shape_81},{t:this.shape_49,p:{y:139.2}}]},1).to({state:[{t:this.shape_50,p:{y:138.7,x:233.6}},{t:this.shape_82},{t:this.shape_49,p:{y:139.4}}]},1).to({state:[{t:this.shape_54,p:{x:237,y:165.9}},{t:this.shape_53,p:{x:270.5,y:165}},{t:this.shape_52,p:{x:251.7,y:171.4}},{t:this.shape_51},{t:this.shape_50,p:{y:138.8,x:233.6}},{t:this.shape_49,p:{y:139.5}}]},1).wait(37));

	// hair
	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#DD9297").s().p("AlQE2QgJhzBMi4QBLizBqh+QBziKBaAKQBbAKA5A8QA0A4AQBcQAOBXgWBnQgXBng5BgQhgChi5A2Qg6AQg8AEIgwABQgRADgPAAQhdAAgJhyg");
	this.shape_83.setTransform(233.8,115.1);

	this.timeline.addTween(cjs.Tween.get(this.shape_83).wait(96));

	// face
	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#FFF5CF").s().p("AicHCQiVg/gli7QgXhxAMh0QALh1AqhiQBgjcC+gLQC9gMBrC2QBmCsgjDZQgJA5gRAxQgcBQgxA8QgVAagZAXQhgBWh2ALIgWABQg5AAg/gbg");
	this.shape_84.setTransform(255.5,158);

	this.timeline.addTween(cjs.Tween.get(this.shape_84).wait(96));

	// hair
	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#DD9297").s().p("AsZLeQgugjgXgtIgOgnQgLiCCKhjQAygkBQgoQAugWBZgpQA7gcASgrQAPgjgHg+IgVh/QgNhZAFhLQALixBpiQQBjiHCZhIQCbhJCfgCQCwgDChBWQCkBYBNDaQBLDSgwDMQgxDNh2BQQgmAZgnAJIggAEQh4AihsBPQgZATiaCFQhuBfheAwQiFBEirAUQhQAKhEAAQjMAAhthTg");
	this.shape_85.setTransform(228.7,140);

	this.timeline.addTween(cjs.Tween.get(this.shape_85).wait(96));

	// neck
	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#FFFFFF").s().p("ACIBKQhBgCgtgyIgfgpIApgPQArgPANgCQA1gIAjARQAqAUgKAuQgKAyg8AAIgGAAgAjVAUQgDgqAdgbQAagZAiABQAlABAuAaQAXAOAQANQgoAlgiAaQgkAbgpACIgFAAQgwAAgEg1gAgFgTIAAAAg");
	this.shape_86.setTransform(252.6,282);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#FFFFFF").s().p("ABvBiQgbgLg/hKIgPgQQA4guATgSQAhgfAegEQAqgFALA8QAMBFgbAvQgUAigcAAQgLAAgMgFgAicBSQg0gMAKhLQAJhGA5gFQAdgCAbALQAfAKAzA6IhMA9QggAagiAAQgKAAgKgCgAAGgDIAAAAg");
	this.shape_87.setTransform(252.1,252.8);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#FFFFFF").s().p("AjqCpQg9gGgvgmQgvglgKgyQgRhZBZg6QAsgdAwgLIG/gUQBTAJA0AqQAuAnAIA1QAIAzggArQgkAuhFAQQh4AbhYhBQgbgUgVgbIgQgXQgpBUhDAmQgwAag1AAIgZgBg");
	this.shape_88.setTransform(254.2,206.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_88},{t:this.shape_87},{t:this.shape_86}]}).to({state:[{t:this.shape_88},{t:this.shape_87},{t:this.shape_86}]},14).to({state:[{t:this.shape_88},{t:this.shape_87},{t:this.shape_86}]},10).wait(72));

	// hand L
	this.instance = new lib.handtool("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(219.2,218.8,1,1,1.2,0,0,185.7,18.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:7.7,x:219.1},14).wait(10).to({startPosition:0},0).wait(20).to({startPosition:0},0).to({rotation:1.2,x:219.2},15).wait(37));

	// hand R
	this.instance_1 = new lib.hand("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(324.5,290,1,1,0,0,0,16,25.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({rotation:-105,x:359.4,y:277.1},14).to({regY:26,rotation:-120,x:359.5,y:277},10).to({regY:25.9,rotation:-105,x:359.4,y:277.1},10).to({regY:26,rotation:-120,x:359.5,y:277},10).to({regY:25.9,rotation:0,x:324.5,y:290},15).wait(37));

	// hand Top
	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#81B2E0").s().p("ACDIzQhUgCg4hAQgvg0hSizQhRi0g/i9QhHjUgMh5QgNiOBIASQChApDQEWQCOC8B8DqQA1BlgUBeQgSBUhEA1QhAAyhLAAIgGAAg");
	this.shape_89.setTransform(312.2,253.8);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#81B2E0").s().p("AAGHsQgvgzhWiwQhWiwhEi6QhNjRgPh4QgSiMBJAQQChAkDXEOQCSC2CCDlQA4BkgRBeQgPBThDA3QhAA1hPABIgCAAQhSAAg6g9g");
	this.shape_90.setTransform(312.8,253.3);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#81B2E0").s().p("AAXHmQgwgxhbisQhbithJi3QhTjNgSh3QgWiMBJAOQChAgDeEGQCWCxCJDgQA6BhgOBeQgNBUhBA4Qg+A3hOADIgJAAQhNAAg5g5g");
	this.shape_91.setTransform(313.3,252.7);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#81B2E0").s().p("AAoHhQgxgwhgioQhfiphPi1QhYjKgWh2QgaiKBJAMQChAaDlD+QCbCtCODaQA+BggMBeQgKBTg/A6Qg8A5hOAFIgPAAQhJAAg4g0g");
	this.shape_92.setTransform(313.8,252.2);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#81B2E0").s().p("AA4HbQgzguhkilQhjimhVixQhdjHgZh1QgeiJBJAKQChAVDsD3QCfCnCUDWQBBBcgJBeQgIBUg9A8Qg6A6hNAHIgUABQhGAAg4gwg");
	this.shape_93.setTransform(314.4,251.7);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#81B2E0").s().p("ABKHVQg1gshoiiQhpiihZiuQhkjDgdh0QghiIBJAIQChAQDzDvQCkChCaDRQBDBbgGBeQgFBTg7A+Qg4A8hNAJQgOACgNAAQhCAAg1gtg");
	this.shape_94.setTransform(314.9,251.1);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f("#81B2E0").s().p("ABaHPQg2gqhtieQhtifhfirQhpjAgghzQgmiHBJAGQCiALD5DnQCpCdCgDLQBFBZgCBeQgDBTg5BAQg3A9hMAMQgQACgQAAQg+AAg1gpg");
	this.shape_95.setTransform(315.5,250.6);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.f("#81B2E0").s().p("ABrHJQg4gohxibQhyibhkipQhvi8gjhyQgqiFBJADQCiAHEADfQCtCXCnDGQBIBXAABeQgBBTg3BBQg0A/hMAOQgUAEgSAAQg7AAgzgmg");
	this.shape_96.setTransform(316.1,250.1);

	this.shape_97 = new cjs.Shape();
	this.shape_97.graphics.f("#81B2E0").s().p("AB7HEQg5gnh2iYQh2iXhpimQh1i5gnhwQguiEBKAAQCiACEHDXQCyCSCsDCQBLBUACBeQADBUg1BCQgzBBhMAQQgWAFgVAAQg4AAgygig");
	this.shape_97.setTransform(316.6,249.6);

	this.shape_98 = new cjs.Shape();
	this.shape_98.graphics.f("#81B2E0").s().p("ACLG+Qg6gmh7iTQh7iVhtiiQh7i2gqhvQgyiDBJgCQCigDEODQQC2CNCzC8QBNBSAGBeQAFBUg0BEQgwBChLATQgZAGgYAAQg1AAgxgfg");
	this.shape_98.setTransform(317.2,249.1);

	this.shape_99 = new cjs.Shape();
	this.shape_99.graphics.f("#81B2E0").s().p("ACcG4Qg7gkiAiQQiAiRhyigQiBiyguhuQg2iCBKgEQCigHEVDHQC7CIC4C3QBQBQAJBeQAHBUgxBFQgvBEhLAVQgbAIgbAAQgyAAgvgcg");
	this.shape_99.setTransform(317.8,248.6);

	this.shape_100 = new cjs.Shape();
	this.shape_100.graphics.f("#81B2E0").s().p("ACsGyQg8giiEiNQiFiOh4icQiGivgyhtQg5iBBJgFQCjgNEbDAQDACCC+CyQBTBOALBeQAKBTgvBIQgtBFhKAYQgeAJgdAAQgwAAgugZg");
	this.shape_100.setTransform(318.4,248.1);

	this.shape_101 = new cjs.Shape();
	this.shape_101.graphics.f("#81B2E0").s().p("AC9GsQg+ghiJiJQiJiKh9iZQiMisg1hsQg+h/BKgIQCjgSEiC4QDEB9DECtQBWBMAOBeQAMBTgtBKQgrBGhKAaQggAMggAAQgtAAgsgXg");
	this.shape_101.setTransform(318.9,247.6);

	this.shape_102 = new cjs.Shape();
	this.shape_102.graphics.f("#81B2E0").s().p("ADNGmQg/geiOiGQiNiHiDiWQiRipg5hrQhBh+BJgKQCjgWEqCwQDIB4DKCoQBYBJARBeQAPBUgrBLQgpBIhJAcQgjANgjAAQgrAAgqgUg");
	this.shape_102.setTransform(319.5,247);

	this.shape_103 = new cjs.Shape();
	this.shape_103.graphics.f("#81B2E0").s().p("ADdGgQhAgdiUiCQiRiDiIiUQiXilg8hqQhGh8BKgNQCjgbExCoQDMBzDRCkQBaBGAUBeQASBUgqBMQgnBKhJAfQglAQglAAQgpAAgogTg");
	this.shape_103.setTransform(320.2,246.5);

	this.shape_104 = new cjs.Shape();
	this.shape_104.graphics.f("#81B2E0").s().p("ADOGmQg/gfiPiFQiNiHiDiWQiRiog5hrQhCh+BJgKQCjgXEqCwQDJB3DLCoQBYBJARBeQAPBUgrBLQgpBIhJAdQgkANgiAAQgrAAgqgUg");
	this.shape_104.setTransform(319.6,247);

	this.shape_105 = new cjs.Shape();
	this.shape_105.graphics.f("#81B2E0").s().p("AC/GrQg+ggiKiJQiJiKh+iYQiNisg1hsQg/h+BKgJQCjgTEkC3QDEB9DFCsQBVBMAPBeQANBTgtBKQgrBHhKAaQggAMghAAQgsAAgsgXg");
	this.shape_105.setTransform(319,247.5);

	this.shape_106 = new cjs.Shape();
	this.shape_106.graphics.f("#81B2E0").s().p("ACwGxQg9giiFiMQiGiNh5icQiHiugyhtQg7iABKgHQCigNEdC+QDBCBC/CxQBTBOAMBeQALBTgvBIQgtBGhKAYQgeAKgeAAQgvAAgtgZg");
	this.shape_106.setTransform(318.5,248);

	this.shape_107 = new cjs.Shape();
	this.shape_107.graphics.f("#81B2E0").s().p("ACgG2Qg8gjiAiQQiBiQh1ieQiBiygvhuQg3iBBJgEQCjgKEWDGQC8CGC6C2QBRBPAJBeQAIBUgxBGQguBEhKAWQgcAJgbAAQgyAAgvgcg");
	this.shape_107.setTransform(318,248.5);

	this.shape_108 = new cjs.Shape();
	this.shape_108.graphics.f("#81B2E0").s().p("ACRG8Qg6glh9iTQh8iThwihQh8i1gshvQgziDBJgCQCjgEEPDMQC5CLC0C7QBOBSAHBeQAFBTgyBFQgwBChLAUQgaAHgZAAQg0AAgwgeg");
	this.shape_108.setTransform(317.4,248.9);

	this.shape_109 = new cjs.Shape();
	this.shape_109.graphics.f("#81B2E0").s().p("ACCHBQg6gmh4iWQh4iWhrikQh3i4gohwQgwiEBKAAQCiAAEJDUQC0CQCvC/QBLBUAEBeQAEBTg1BEQgxBBhMARQgWAFgWAAQg3AAgyghg");
	this.shape_109.setTransform(316.9,249.4);

	this.shape_110 = new cjs.Shape();
	this.shape_110.graphics.f("#81B2E0").s().p("AByHHQg4gohziZQh0iahminQhyi7glhxQgsiFBJACQCiAFEDDbQCwCVCpDEQBJBVACBeQABBUg3BCQgzA/hMAQQgUAEgUAAQg6AAgzgkg");
	this.shape_110.setTransform(316.3,249.9);

	this.shape_111 = new cjs.Shape();
	this.shape_111.graphics.f("#81B2E0").s().p("ABjHMQg3gphvidQhwichhiqQhsi+gihyQgoiGBJAEQCiAJD9DjQCrCZCjDJQBHBYgBBeQgCBTg3BAQg2A+hMANQgTADgRAAQg8AAg0gng");
	this.shape_111.setTransform(315.8,250.3);

	this.shape_112 = new cjs.Shape();
	this.shape_112.graphics.f("#81B2E0").s().p("ABTHSQg1grhrigQhrighditQhnjBgfhzQgkiHBJAGQCiAOD2DqQCnCeCeDOQBFBZgEBeQgEBUg6A+Qg3A9hNALQgQACgPAAQg/AAg1gqg");
	this.shape_112.setTransform(315.3,250.8);

	this.shape_113 = new cjs.Shape();
	this.shape_113.graphics.f("#81B2E0").s().p("ABEHXQg1gthmijQhnijhYivQhhjFgch0QggiIBJAIQChASDwDyQCjCjCYDSQBCBcgHBeQgGBTg7A+Qg5A7hNAIQgNACgMAAQhDAAg2gug");
	this.shape_113.setTransform(314.8,251.3);

	this.shape_114 = new cjs.Shape();
	this.shape_114.graphics.f("#81B2E0").s().p("AA1HdQg0gvhiimQhjimhSiyQhdjIgYh1QgdiJBJAKQChAXDqD4QCfCpCSDXQBABdgKBeQgIBUg9A7Qg7A6hOAGIgTABQhGAAg3gxg");
	this.shape_114.setTransform(314.2,251.8);

	this.shape_115 = new cjs.Shape();
	this.shape_115.graphics.f("#81B2E0").s().p("AAkHiQgxgwhfipQheiqhOi1QhXjLgVh2QgZiKBJAMQChAbDkEAQCaCtCNDcQA9BggMBeQgLBTg/A6Qg9A4hOAFIgOAAQhJAAg5g1g");
	this.shape_115.setTransform(313.8,252.3);

	this.shape_116 = new cjs.Shape();
	this.shape_116.graphics.f("#81B2E0").s().p("AAVHnQgwgxhaitQhaithJi3QhSjOgSh3QgViMBJAOQChAgDdEHQCWCyCHDhQA7BhgPBeQgNBUhBA4Qg/A3hOACIgIAAQhOAAg5g5g");
	this.shape_116.setTransform(313.2,252.8);

	this.shape_117 = new cjs.Shape();
	this.shape_117.graphics.f("#81B2E0").s().p("AAFHsQgvgzhWiwQhViwhEi6QhNjSgOh4QgSiMBJAQQChAkDXEPQCRC3CCDlQA4BkgRBeQgQBThDA3QhAA1hPAAIgCAAQhSAAg6g9g");
	this.shape_117.setTransform(312.7,253.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_89}]}).to({state:[{t:this.shape_90}]},1).to({state:[{t:this.shape_91}]},1).to({state:[{t:this.shape_92}]},1).to({state:[{t:this.shape_93}]},1).to({state:[{t:this.shape_94}]},1).to({state:[{t:this.shape_95}]},1).to({state:[{t:this.shape_96}]},1).to({state:[{t:this.shape_97}]},1).to({state:[{t:this.shape_98}]},1).to({state:[{t:this.shape_99}]},1).to({state:[{t:this.shape_100}]},1).to({state:[{t:this.shape_101}]},1).to({state:[{t:this.shape_102}]},1).to({state:[{t:this.shape_103}]},1).to({state:[{t:this.shape_103}]},10).to({state:[{t:this.shape_103}]},20).to({state:[{t:this.shape_104}]},1).to({state:[{t:this.shape_105}]},1).to({state:[{t:this.shape_106}]},1).to({state:[{t:this.shape_107}]},1).to({state:[{t:this.shape_108}]},1).to({state:[{t:this.shape_109}]},1).to({state:[{t:this.shape_110}]},1).to({state:[{t:this.shape_111}]},1).to({state:[{t:this.shape_112}]},1).to({state:[{t:this.shape_113}]},1).to({state:[{t:this.shape_114}]},1).to({state:[{t:this.shape_115}]},1).to({state:[{t:this.shape_116}]},1).to({state:[{t:this.shape_117}]},1).to({state:[{t:this.shape_89}]},1).wait(37));

	// cloth
	this.shape_118 = new cjs.Shape();
	this.shape_118.graphics.f("#5E9BD4").s().p("AgqIyIgJgbQAjjUAImwIABmHQgFg8AggBQAMgBAJALQALALAAAQQAABngRFdQgUG1gWBmQgVBfgNAAIgBAAg");
	this.shape_118.setTransform(252.4,253.7);

	this.shape_119 = new cjs.Shape();
	this.shape_119.graphics.f("#81B2E0").s().p("AslUnQiPiQAXkDQAPiqBwjrQAkhKBHiGQBSiZAghAQBci4BjnGQAfiOAciYIAWh7QgOiGAmiHQBNkNEGgCQELgDBQDeQAaBLAGBmQADA2gCBMQACCmAnDlQA7FeB0DlQChE+BEEJQBXFUhLDhQgjBpgtA6Qg3BGhgAqQjGBUonAMIgzAAQngAAi9i/g");
	this.shape_119.setTransform(248.6,348.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_119},{t:this.shape_118}]}).to({state:[{t:this.shape_119},{t:this.shape_118}]},14).to({state:[{t:this.shape_119},{t:this.shape_118}]},10).wait(72));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(279.1,308.3,412.3,468.7);
// library properties:
lib.properties = {
	id: 'EC43A663D1A440C3ADAF9725EE4961C8',
	width: 500,
	height: 550,
	fps: 24,
	color: "#000000",
	opacity: 0.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['EC43A663D1A440C3ADAF9725EE4961C8'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;